In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('Resources_k/bins_k_means_classes.csv')
df

,Unnamed: 0,fire_id,fire_size,fire_cause,latitude,longitude,state,discovery_month,Temp_pre_30,Temp_pre_15,...,Hum_pre_30,Hum_pre_15,Hum_pre_7,year,putout_time,fire_size_bin,fire_size_bin_no,km_scaled_class7,km_scaled_class15,km_scaled_class30
0,0,3,1.00,Debris Burning,39.641400,-119.308300,NV,Jun,16.275967,18.996181,...,44.778429,37.140811,35.353846,2005,0,Teacup,1,2,1,1
1,1,24,40.00,Arson,31.435181,-88.999489,MS,Apr,13.468619,15.067227,...,57.997207,56.747191,59.614458,1999,0,Mini,3,0,0,0
2,2,31,1.20,Debris Burning,48.833000,-99.783600,ND,Apr,-0.891635,0.372659,...,77.575012,75.963981,71.173116,2007,0,Teacup,1,2,2,2
3,3,35,30.18,Debris Burning,31.259000,-84.895600,GA,Oct,20.079480,17.722714,...,67.551783,61.733788,60.328571,2000,0,Mini,3,0,0,1
4,4,36,1420.00,Lightning,33.241800,-104.912200,NM,Jul,31.055859,32.523438,...,28.783203,25.789062,18.208333,1994,1,Large,5,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13133,13133,55336,3409.00,Utilities,31.059000,-98.956367,TX,Aug,30.731860,30.545367,...,50.089157,49.416505,55.426471,2015,3,Large,5,1,1,1
13134,13134,55337,4582.00,Utilities,30.075167,-97.149167,TX,Oct,24.642268,23.713390,...,62.848172,60.641975,63.196819,2015,11,Large,5,0,0,0
13135,13135,55341,17823.00,Accidental,44.834600,-117.220600,OR,Sep,15.546194,12.890633,...,55.009259,62.368700,67.266304,2015,39,XL,6,0,0,1
13136,13136,55342,5086.00,Debris Burning,45.656100,-109.114200,MT,Mar,2.275974,7.360185,...,51.676681,46.933399,42.638384,2015,5,Large,5,2,2,2
13137,13137,55343,5963.00,Debris Burning,43.785671,-115.985922,ID,Oct,17.007551,16.983670,...,51.541802,53.945191,56.257500,2015,10,Large,5,0,0,0

In [3]:
df

,Unnamed: 0,fire_id,fire_size,fire_cause,latitude,longitude,state,discovery_month,Temp_pre_30,Temp_pre_15,...,Hum_pre_30,Hum_pre_15,Hum_pre_7,year,putout_time,fire_size_bin,fire_size_bin_no,km_scaled_class7,km_scaled_class15,km_scaled_class30
0,0,3,1.00,Debris Burning,39.641400,-119.308300,NV,Jun,16.275967,18.996181,...,44.778429,37.140811,35.353846,2005,0,Teacup,1,2,1,1
1,1,24,40.00,Arson,31.435181,-88.999489,MS,Apr,13.468619,15.067227,...,57.997207,56.747191,59.614458,1999,0,Mini,3,0,0,0
2,2,31,1.20,Debris Burning,48.833000,-99.783600,ND,Apr,-0.891635,0.372659,...,77.575012,75.963981,71.173116,2007,0,Teacup,1,2,2,2
3,3,35,30.18,Debris Burning,31.259000,-84.895600,GA,Oct,20.079480,17.722714,...,67.551783,61.733788,60.328571,2000,0,Mini,3,0,0,1
4,4,36,1420.00,Lightning,33.241800,-104.912200,NM,Jul,31.055859,32.523438,...,28.783203,25.789062,18.208333,1994,1,Large,5,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13133,13133,55336,3409.00,Utilities,31.059000,-98.956367,TX,Aug,30.731860,30.545367,...,50.089157,49.416505,55.426471,2015,3,Large,5,1,1,1
13134,13134,55337,4582.00,Utilities,30.075167,-97.149167,TX,Oct,24.642268,23.713390,...,62.848172,60.641975,63.196819,2015,11,Large,5,0,0,0
13135,13135,55341,17823.00,Accidental,44.834600,-117.220600,OR,Sep,15.546194,12.890633,...,55.009259,62.368700,67.266304,2015,39,XL,6,0,0,1
13136,13136,55342,5086.00,Debris Burning,45.656100,-109.114200,MT,Mar,2.275974,7.360185,...,51.676681,46.933399,42.638384,2015,5,Large,5,2,2,2
13137,13137,55343,5963.00,Debris Burning,43.785671,-115.985922,ID,Oct,17.007551,16.983670,...,51.541802,53.945191,56.257500,2015,10,Large,5,0,0,0

In [4]:
df['medium_plus']=''

In [5]:
df.loc[df['fire_size_bin_no']>=4,'medium_plus']=1
df.loc[df['fire_size_bin_no']<4,'medium_plus']=0
df['medium_plus']=df["medium_plus"].astype(int)
df

,Unnamed: 0,fire_id,fire_size,fire_cause,latitude,longitude,state,discovery_month,Temp_pre_30,Temp_pre_15,...,Hum_pre_15,Hum_pre_7,year,putout_time,fire_size_bin,fire_size_bin_no,km_scaled_class7,km_scaled_class15,km_scaled_class30,medium_plus
0,0,3,1.00,Debris Burning,39.641400,-119.308300,NV,Jun,16.275967,18.996181,...,37.140811,35.353846,2005,0,Teacup,1,2,1,1,0
1,1,24,40.00,Arson,31.435181,-88.999489,MS,Apr,13.468619,15.067227,...,56.747191,59.614458,1999,0,Mini,3,0,0,0,0
2,2,31,1.20,Debris Burning,48.833000,-99.783600,ND,Apr,-0.891635,0.372659,...,75.963981,71.173116,2007,0,Teacup,1,2,2,2,0
3,3,35,30.18,Debris Burning,31.259000,-84.895600,GA,Oct,20.079480,17.722714,...,61.733788,60.328571,2000,0,Mini,3,0,0,1,0
4,4,36,1420.00,Lightning,33.241800,-104.912200,NM,Jul,31.055859,32.523438,...,25.789062,18.208333,1994,1,Large,5,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13133,13133,55336,3409.00,Utilities,31.059000,-98.956367,TX,Aug,30.731860,30.545367,...,49.416505,55.426471,2015,3,Large,5,1,1,1,1
13134,13134,55337,4582.00,Utilities,30.075167,-97.149167,TX,Oct,24.642268,23.713390,...,60.641975,63.196819,2015,11,Large,5,0,0,0,1
13135,13135,55341,17823.00,Accidental,44.834600,-117.220600,OR,Sep,15.546194,12.890633,...,62.368700,67.266304,2015,39,XL,6,0,0,1,1
13136,13136,55342,5086.00,Debris Burning,45.656100,-109.114200,MT,Mar,2.275974,7.360185,...,46.933399,42.638384,2015,5,Large,5,2,2,2,1
13137,13137,55343,5963.00,Debris Burning,43.785671,-115.985922,ID,Oct,17.007551,16.983670,...,53.945191,56.257500,2015,10,Large,5,0,0,0,1

In [6]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['discovery_month_no'] = le.fit_transform(df["discovery_month"])
df.head()

,Unnamed: 0,fire_id,fire_size,fire_cause,latitude,longitude,state,discovery_month,Temp_pre_30,Temp_pre_15,...,Hum_pre_7,year,putout_time,fire_size_bin,fire_size_bin_no,km_scaled_class7,km_scaled_class15,km_scaled_class30,medium_plus,discovery_month_no
0,0,3,1.00,Debris Burning,39.641400,-119.308300,NV,Jun,16.275967,18.996181,...,35.353846,2005,0,Teacup,1,2,1,1,0,6
1,1,24,40.00,Arson,31.435181,-88.999489,MS,Apr,13.468619,15.067227,...,59.614458,1999,0,Mini,3,0,0,0,0,0
2,2,31,1.20,Debris Burning,48.833000,-99.783600,ND,Apr,-0.891635,0.372659,...,71.173116,2007,0,Teacup,1,2,2,2,0,0
3,3,35,30.18,Debris Burning,31.259000,-84.895600,GA,Oct,20.079480,17.722714,...,60.328571,2000,0,Mini,3,0,0,1,0,10
4,4,36,1420.00,Lightning,33.241800,-104.912200,NM,Jul,31.055859,32.523438,...,18.208333,1994,1,Large,5,1,1,1,1,5

In [7]:
# Months dictionary
months_num = {
    "Jan": 1,
    "Feb": 2,
    "Mar": 3,
    "Apr": 4,
    "May": 5,
    "Jun": 6,
    "Jul": 7,
    "Aug": 8,
    "Sep": 9,
    "Oct": 10,
    "Nov": 11,
    "Dec": 12,
}

# Months' names encoded using the dictionary values
df["discovery_month_no"] = df["discovery_month"].apply(lambda x: months_num[x])
df.head()

,Unnamed: 0,fire_id,fire_size,fire_cause,latitude,longitude,state,discovery_month,Temp_pre_30,Temp_pre_15,...,Hum_pre_7,year,putout_time,fire_size_bin,fire_size_bin_no,km_scaled_class7,km_scaled_class15,km_scaled_class30,medium_plus,discovery_month_no
0,0,3,1.00,Debris Burning,39.641400,-119.308300,NV,Jun,16.275967,18.996181,...,35.353846,2005,0,Teacup,1,2,1,1,0,6
1,1,24,40.00,Arson,31.435181,-88.999489,MS,Apr,13.468619,15.067227,...,59.614458,1999,0,Mini,3,0,0,0,0,4
2,2,31,1.20,Debris Burning,48.833000,-99.783600,ND,Apr,-0.891635,0.372659,...,71.173116,2007,0,Teacup,1,2,2,2,0,4
3,3,35,30.18,Debris Burning,31.259000,-84.895600,GA,Oct,20.079480,17.722714,...,60.328571,2000,0,Mini,3,0,0,1,0,10
4,4,36,1420.00,Lightning,33.241800,-104.912200,NM,Jul,31.055859,32.523438,...,18.208333,1994,1,Large,5,1,1,1,1,7

In [8]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['state_no'] = le.fit_transform(df["state"])
df

,Unnamed: 0,fire_id,fire_size,fire_cause,latitude,longitude,state,discovery_month,Temp_pre_30,Temp_pre_15,...,year,putout_time,fire_size_bin,fire_size_bin_no,km_scaled_class7,km_scaled_class15,km_scaled_class30,medium_plus,discovery_month_no,state_no
0,0,3,1.00,Debris Burning,39.641400,-119.308300,NV,Jun,16.275967,18.996181,...,2005,0,Teacup,1,2,1,1,0,6,28
1,1,24,40.00,Arson,31.435181,-88.999489,MS,Apr,13.468619,15.067227,...,1999,0,Mini,3,0,0,0,0,4,21
2,2,31,1.20,Debris Burning,48.833000,-99.783600,ND,Apr,-0.891635,0.372659,...,2007,0,Teacup,1,2,2,2,0,4,24
3,3,35,30.18,Debris Burning,31.259000,-84.895600,GA,Oct,20.079480,17.722714,...,2000,0,Mini,3,0,0,1,0,10,7
4,4,36,1420.00,Lightning,33.241800,-104.912200,NM,Jul,31.055859,32.523438,...,1994,1,Large,5,1,1,1,1,7,27
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13133,13133,55336,3409.00,Utilities,31.059000,-98.956367,TX,Aug,30.731860,30.545367,...,2015,3,Large,5,1,1,1,1,8,38
13134,13134,55337,4582.00,Utilities,30.075167,-97.149167,TX,Oct,24.642268,23.713390,...,2015,11,Large,5,0,0,0,1,10,38
13135,13135,55341,17823.00,Accidental,44.834600,-117.220600,OR,Sep,15.546194,12.890633,...,2015,39,XL,6,0,0,1,1,9,32
13136,13136,55342,5086.00,Debris Burning,45.656100,-109.114200,MT,Mar,2.275974,7.360185,...,2015,5,Large,5,2,2,2,1,3,22
13137,13137,55343,5963.00,Debris Burning,43.785671,-115.985922,ID,Oct,17.007551,16.983670,...,2015,10,Large,5,0,0,0,1,10,9

In [9]:
states_num = {
    "AK": 1,
    "AL": 2,
    "AR": 3,
    "AZ": 4,
    "CA": 5,
    "CO": 6,
    "FL": 7,
    "GA": 8,
    "IA": 9,
    "ID": 10,
    "IL": 11,
    "IN": 12,
    "KS": 13,
    "KY": 14,
    "LA": 15,
    "MA": 16,
    "MD": 17,
    "ME": 18,
    "MI": 19,
    "MN": 20,
    "MO": 21,
    "MS": 22,
    "MT": 23,
    "NC": 24,
    "ND": 25,
    "NE": 26,
    "NJ": 27,
    "NM": 28,
    "NV": 29,
    "NY": 30,
    "OH": 31,
    "OK": 32,
    "OR": 33,
    "PA": 34,
    "PR": 35,
    "SC": 36,
    "SD": 37,
    "TN": 38,
    "TX": 39,
    "UT": 40,
    "VA": 41,
    "WA": 42,
    "WI": 43,
    "WV": 44,
    "WY": 45
    
}

In [10]:
# States' names encoded using the dictionary values
df["state_no"] = df["state"].apply(lambda x: states_num[x])
df.head()

,Unnamed: 0,fire_id,fire_size,fire_cause,latitude,longitude,state,discovery_month,Temp_pre_30,Temp_pre_15,...,year,putout_time,fire_size_bin,fire_size_bin_no,km_scaled_class7,km_scaled_class15,km_scaled_class30,medium_plus,discovery_month_no,state_no
0,0,3,1.00,Debris Burning,39.641400,-119.308300,NV,Jun,16.275967,18.996181,...,2005,0,Teacup,1,2,1,1,0,6,29
1,1,24,40.00,Arson,31.435181,-88.999489,MS,Apr,13.468619,15.067227,...,1999,0,Mini,3,0,0,0,0,4,22
2,2,31,1.20,Debris Burning,48.833000,-99.783600,ND,Apr,-0.891635,0.372659,...,2007,0,Teacup,1,2,2,2,0,4,25
3,3,35,30.18,Debris Burning,31.259000,-84.895600,GA,Oct,20.079480,17.722714,...,2000,0,Mini,3,0,0,1,0,10,8
4,4,36,1420.00,Lightning,33.241800,-104.912200,NM,Jul,31.055859,32.523438,...,1994,1,Large,5,1,1,1,1,7,28

In [11]:
df.columns

Index(['Unnamed: 0', 'fire_id', 'fire_size', 'fire_cause', 'latitude',
       'longitude', 'state', 'discovery_month', 'Temp_pre_30', 'Temp_pre_15',
       'Temp_pre_7', 'Wind_pre_30', 'Wind_pre_15', 'Wind_pre_7', 'Hum_pre_30',
       'Hum_pre_15', 'Hum_pre_7', 'year', 'putout_time', 'fire_size_bin',
       'fire_size_bin_no', 'km_scaled_class7', 'km_scaled_class15',
       'km_scaled_class30', 'medium_plus', 'discovery_month_no', 'state_no'],
      dtype='object')

In [13]:
df_all=df[['fire_id', 'fire_size', 'fire_cause', 'latitude', 'longitude', 'state', 'state_no', 'discovery_month', 'discovery_month_no', 'year', 'putout_time', 'Temp_pre_30', 'Temp_pre_15',
       'Temp_pre_7', 'Wind_pre_30', 'Wind_pre_15', 'Wind_pre_7', 'Hum_pre_30',
       'Hum_pre_15', 'Hum_pre_7',  'fire_size_bin',  'fire_size_bin_no',
       'medium_plus']]
df_all

,fire_id,fire_size,fire_cause,latitude,longitude,state,state_no,discovery_month,discovery_month_no,year,...,Temp_pre_7,Wind_pre_30,Wind_pre_15,Wind_pre_7,Hum_pre_30,Hum_pre_15,Hum_pre_7,fire_size_bin,fire_size_bin_no,medium_plus
0,3,1.00,Debris Burning,39.641400,-119.308300,NV,29,Jun,6,2005,...,18.142564,4.054982,3.398329,3.671282,44.778429,37.140811,35.353846,Teacup,1,0
1,24,40.00,Arson,31.435181,-88.999489,MS,22,Apr,4,1999,...,15.604790,2.038268,1.737921,1.775904,57.997207,56.747191,59.614458,Mini,3,0
2,31,1.20,Debris Burning,48.833000,-99.783600,ND,25,Apr,4,2007,...,-4.273834,5.800667,6.012852,6.658621,77.575012,75.963981,71.173116,Teacup,1,0
3,35,30.18,Debris Burning,31.259000,-84.895600,GA,8,Oct,10,2000,...,18.188679,3.659840,3.366443,2.211429,67.551783,61.733788,60.328571,Mini,3,0
4,36,1420.00,Lightning,33.241800,-104.912200,NM,28,Jul,7,1994,...,34.893333,4.026367,3.844922,3.695833,28.783203,25.789062,18.208333,Large,5,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13133,55336,3409.00,Utilities,31.059000,-98.956367,TX,39,Aug,8,2015,...,28.719917,3.136761,3.238803,3.224274,50.089157,49.416505,55.426471,Large,5,1
13134,55337,4582.00,Utilities,30.075167,-97.149167,TX,39,Oct,10,2015,...,24.221869,1.529850,1.576828,1.563817,62.848172,60.641975,63.196819,Large,5,1
13135,55341,17823.00,Accidental,44.834600,-117.220600,OR,33,Sep,9,2015,...,10.734328,2.608150,2.486802,1.835821,55.009259,62.368700,67.266304,XL,6,1
13136,55342,5086.00,Debris Burning,45.656100,-109.114200,MT,23,Mar,3,2015,...,7.678571,4.428757,4.197593,3.803571,51.676681,46.933399,42.638384,Large,5,1
13137,55343,5963.00,Debris Burning,43.785671,-115.985922,ID,10,Oct,10,2015,...,15.732906,1.580406,1.835639,1.405983,51.541802,53.945191,56.257500,Large,5,1

In [14]:
#df_all.to_csv('Resources_k/df_all_k.csv', index=False)

In [134]:
df_all.columns

Index(['fire_id', 'fire_size', 'fire_cause', 'state', 'state_no',
       'discovery_month', 'discovery_month_no', 'year', 'putout_time',
       'Temp_pre_30', 'Temp_pre_15', 'Temp_pre_7', 'Wind_pre_30',
       'Wind_pre_15', 'Wind_pre_7', 'Hum_pre_30', 'Hum_pre_15', 'Hum_pre_7',
       'fire_size_bin', 'fire_size_bin_no', 'medium_plus'],
      dtype='object')

In [149]:
df7_k=df_all.drop(columns=['fire_size', 'fire_cause', 'state_no',
       'discovery_month_no', 'year', 'putout_time','fire_size_bin', 'Temp_pre_30', 'Temp_pre_15', 'Wind_pre_30',
       'Wind_pre_15', 'Hum_pre_30', 'Hum_pre_15'], axis=1)
#df7_k.to_csv('Resources_k/df7_k.csv', index=False)

In [147]:
df15_k=df_all.drop(columns=['fire_size', 'fire_cause', 'state',
       'discovery_month', 'year', 'putout_time','fire_size_bin', 'Temp_pre_30', 'Temp_pre_7', 'Wind_pre_30',
       'Wind_pre_7', 'Hum_pre_30', 'Hum_pre_7'], axis=1)
#df15_k.to_csv('Resources_k/df15_k.csv', index=False)

In [148]:
df30_k=df_all.drop(columns=['fire_size', 'fire_cause', 'state',
       'discovery_month', 'year', 'putout_time','fire_size_bin', 'Temp_pre_15', 'Temp_pre_7', 'Wind_pre_15',
       'Wind_pre_7', 'Hum_pre_15', 'Hum_pre_7'], axis=1)
#df30_k.to_csv('Resources_k/df30_k.csv', index=False)

In [15]:
df7_k2=df_all.drop(columns=['fire_size', 'fire_cause', 'state_no',
       'discovery_month_no', 'year', 'putout_time','fire_size_bin', 'Temp_pre_30', 'Temp_pre_15', 'Wind_pre_30',
       'Wind_pre_15', 'Hum_pre_30', 'Hum_pre_15'], axis=1)
#df7_k2.to_csv('Resources_k/df7_k2.csv', index=False)