# Machine Learning Attempts

-------------------------------------

### Neural Networking

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder
import tensorflow as tf

import pandas as pd
from pathlib import Path

KeyboardInterrupt:

In [ ]:
# Import our input dataset
data = Path('Resources_k/df7_k.csv')
df = pd.read_csv(data)
df.head()

,fire_id,state_no,discovery_month_no,Temp_pre_7,Wind_pre_7,Hum_pre_7,fire_size_bin_no,medium_plus
0,3,29,6,18.142564,3.671282,35.353846,1,0
1,24,22,4,15.604790,1.775904,59.614458,3,0
2,31,25,4,-4.273834,6.658621,71.173116,1,0
3,35,8,10,18.188679,2.211429,60.328571,3,0
4,36,28,7,34.893333,3.695833,18.208333,5,1

In [ ]:
df=df.drop(columns=['fire_id', "fire_size_bin_no"])
df

,state_no,discovery_month_no,Temp_pre_7,Wind_pre_7,Hum_pre_7,medium_plus
0,29,6,18.142564,3.671282,35.353846,0
1,22,4,15.604790,1.775904,59.614458,0
2,25,4,-4.273834,6.658621,71.173116,0
3,8,10,18.188679,2.211429,60.328571,0
4,28,7,34.893333,3.695833,18.208333,1
...,...,...,...,...,...,...
13133,39,8,28.719917,3.224274,55.426471,1
13134,39,10,24.221869,1.563817,63.196819,1
13135,33,9,10.734328,1.835821,67.266304,1
13136,23,3,7.678571,3.803571,42.638384,1
13137,10,10,15.732906,1.405983,56.257500,1

In [ ]:
# Remove loan status target from features data
target=df.medium_plus
y=target
# X = df.loc[:, df.columns !=target]
X=df.drop(columns=["medium_plus"]).values

# Split training/test datasets
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

# Create a StandardScaler instance
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [ ]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = len(X_train[0])
hidden_nodes_layer1 = 18
hidden_nodes_layer2 = 12
#hidden_nodes_layer3 = 


nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(
    tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu")
)

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))

# Third hidden layer
#nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer3, activation="relu"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 18)                108

 dense_1 (Dense)             (None, 12)                228

 dense_2 (Dense)             (None, 1)                 13

=================================================================
Total params: 349
Trainable params: 349
Non-trainable params: 0
_________________________________________________________________

In [ ]:
# Compile the model
nn.compile(loss='categorical_crossentropy', optimizer="adam", metrics=["accuracy"])

In [ ]:
## Import checkpoint dependencies
# import os
# from tensorflow.keras.callbacks import ModelCheckpoint

# # Define the checkpoint path and filenames
# os.makedirs("checkpoints/",exist_ok=True)
# checkpoint_path = "checkpoints/weights.{epoch:02d}.hdf5"

# # Create a callback that saves the model's weights every 5 epoch
# cp_callback = ModelCheckpoint(
#     filepath=checkpoint_path,
#     verbose=5,
#     save_weights_only=True,
#     save_freq='epoch')

# Train the model
# fit_model = nn.fit(X_train_scaled,y_train,epochs=100,callbacks=[cp_callback])
fit_model = nn.fit(X_train_scaled,y_train,epochs=50)

# # Restore the model weights
# nn.load_weights("checkpoints/weights.100.hdf5")

Epoch 1/50
308/308 [==============================] - 1s 2ms/step - loss: 0.0000e+00 - accuracy: 0.6291
Epoch 2/50
308/308 [==============================] - 1s 3ms/step - loss: 0.0000e+00 - accuracy: 0.7068
Epoch 3/50
308/308 [==============================] - 1s 2ms/step - loss: 0.0000e+00 - accuracy: 0.7068
Epoch 4/50
308/308 [==============================] - 1s 2ms/step - loss: 0.0000e+00 - accuracy: 0.7068
Epoch 5/50
308/308 [==============================] - 1s 2ms/step - loss: 0.0000e+00 - accuracy: 0.7068
Epoch 6/50
308/308 [==============================] - 1s 3ms/step - loss: 0.0000e+00 - accuracy: 0.7068
Epoch 7/50
308/308 [==============================] - 1s 3ms/step - loss: 0.0000e+00 - accuracy: 0.7068
Epoch 8/50
308/308 [==============================] - 1s 3ms/step - loss: 0.0000e+00 - accuracy: 0.7068
Epoch 9/50
308/308 [==============================] - 1s 3ms/step - loss: 0.0000e+00 - accuracy: 0.7068
Epoch 10/50
308/308 [==============================] - 0s 1ms/step - loss: 0.0000e+00 - accuracy: 0.7068
Epoch 11/50
308/308 [==============================] - 0s 1ms/step - loss: 0.0000e+00 - accuracy: 0.7068
Epoch 12/50
308/308 [==============================] - 1s 3ms/step - loss: 0.0000e+00 - accuracy: 0.7068
Epoch 13/50
308/308 [==============================] - 1s 2ms/step - loss: 0.0000e+00 - accuracy: 0.7068
Epoch 14/50
308/308 [==============================] - 1s 3ms/step - loss: 0.0000e+00 - accuracy: 0.7068
Epoch 15/50
308/308 [==============================] - 1s 3ms/step - loss: 0.0000e+00 - accuracy: 0.7068
Epoch 16/50
308/308 [==============================] - 1s 2ms/step - loss: 0.0000e+00 - accuracy: 0.7068
Epoch 17/50
308/308 [==============================] - 0s 1ms/step - loss: 0.0000e+00 - accuracy: 0.7068
Epoch 18/50
308/308 [==============================] - 0s 1ms/step - loss: 0.0000e+00 - accuracy: 0.7068
Epoch 19/50
308/308 [==============================] - 0s 1ms/step - loss: 0.0000e+00 - accuracy: 0.7068
Epoch 20/50
308/308 [==============================] - 0s 1ms/step - loss: 0.0000e+00 - accuracy: 0.7068
Epoch 21/50
308/308 [==============================] - 0s 1ms/step - loss: 0.0000e+00 - accuracy: 0.7068
Epoch 22/50
308/308 [==============================] - 0s 1ms/step - loss: 0.0000e+00 - accuracy: 0.7068
Epoch 23/50
308/308 [==============================] - 0s 1ms/step - loss: 0.0000e+00 - accuracy: 0.7068
Epoch 24/50
308/308 [==============================] - 0s 1ms/step - loss: 0.0000e+00 - accuracy: 0.7068
Epoch 25/50
308/308 [==============================] - 1s 2ms/step - loss: 0.0000e+00 - accuracy: 0.7068
Epoch 26/50
308/308 [==============================] - 2s 5ms/step - loss: 0.0000e+00 - accuracy: 0.7068
Epoch 27/50
308/308 [==============================] - 1s 2ms/step - loss: 0.0000e+00 - accuracy: 0.7068
Epoch 28/50
308/308 [==============================] - 1s 2ms/step - loss: 0.0000e+00 - accuracy: 0.7068
Epoch 29/50
308/308 [==============================] - 1s 3ms/step - loss: 0.0000e+00 - accuracy: 0.7068
Epoch 30/50
308/308 [==============================] - 1s 3ms/step - loss: 0.0000e+00 - accuracy: 0.7068
Epoch 31/50
308/308 [==============================] - 1s 3ms/step - loss: 0.0000e+00 - accuracy: 0.7068
Epoch 32/50
308/308 [==============================] - 1s 3ms/step - loss: 0.0000e+00 - accuracy: 0.7068
Epoch 33/50
308/308 [==============================] - 0s 1ms/step - loss: 0.0000e+00 - accuracy: 0.7068
Epoch 34/50
308/308 [==============================] - 1s 4ms/step - loss: 0.0000e+00 - accuracy: 0.7068
Epoch 35/50
308/308 [==============================] - 1s 2ms/step - loss: 0.0000e+00 - accuracy: 0.7068
Epoch 36/50
308/308 [==============================] - 1s 3ms/step - loss: 0.0000e+00 - accuracy: 0.7068
Epoch 37/50
308/308 [==============================] - 1s 3ms/step - loss: 0.0000e+00 - accuracy: 0.7068
Epoch 38/50
308/308 [==============================] - 1s 2ms/step - loss: 0.0000e+00 - accuracy: 0.7068
Epoch 39/50
308/308 [==============================] - 1s 2ms/step - loss: 0.0000e+00 - accuracy: 0.7068
Epoch 40/50
308/308 [==============================] - 0s 1ms/step - loss: 0.0000e+00 - accuracy: 0.7068
Epoch 41/50
308/308 [==============================] - 0s 1ms/step - loss: 0.0000e+00 - accuracy: 0.7068
Epoch 42/50
308/308 [==============================] - 0s 1ms/step - loss: 0.0000e+00 - accuracy: 0.7068
Epoch 43/50
308/308 [==============================] - 0s 1ms/step - loss: 0.0000e+00 - accuracy: 0.7068
Epoch 44/50
308/308 [==============================] - 1s 4ms/step - loss: 0.0000e+00 - accuracy: 0.7068
Epoch 45/50
308/308 [==============================] - 1s 4ms/step - loss: 0.0000e+00 - accuracy: 0.7068
Epoch 46/50
308/308 [==============================] - 1s 2ms/step - loss: 0.0000e+00 - accuracy: 0.7068
Epoch 47/50
308/308 [==============================] - 1s 3ms/step - loss: 0.0000e+00 - accuracy: 0.7068
Epoch 48/50
308/308 [==============================] - 1s 2ms/step - loss: 0.0000e+00 - accuracy: 0.7068
Epoch 49/50
308/308 [==============================] - 1s 2ms/step - loss: 0.0000e+00 - accuracy: 0.7068
Epoch 50/50
308/308 [==============================] - 1s 2ms/step - loss: 0.0000e+00 - accuracy: 0.7068

In [ ]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

103/103 - 0s - loss: 0.0000e+00 - accuracy: 0.7002 - 381ms/epoch - 4ms/step
Loss: 0.0, Accuracy: 0.7001522183418274

---------------------

------------------------------

### Random Forest Classifier

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import balanced_accuracy_score
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import confusion_matrix
from imblearn.metrics import classification_report_imbalanced
from sklearn.metrics import classification_report

from pathlib import Path


# Import our input dataset
data = Path('Resources_k/df7_k.csv')
df = pd.read_csv(data)
df

,fire_id,state_no,discovery_month_no,Temp_pre_7,Wind_pre_7,Hum_pre_7,fire_size_bin_no,medium_plus
0,3,29,6,18.142564,3.671282,35.353846,1,0
1,24,22,4,15.604790,1.775904,59.614458,3,0
2,31,25,4,-4.273834,6.658621,71.173116,1,0
3,35,8,10,18.188679,2.211429,60.328571,3,0
4,36,28,7,34.893333,3.695833,18.208333,5,1
...,...,...,...,...,...,...,...,...
13133,55336,39,8,28.719917,3.224274,55.426471,5,1
13134,55337,39,10,24.221869,1.563817,63.196819,5,1
13135,55341,33,9,10.734328,1.835821,67.266304,6,1
13136,55342,23,3,7.678571,3.803571,42.638384,5,1
13137,55343,10,10,15.732906,1.405983,56.257500,5,1

In [ ]:
df=df.drop(columns=['fire_id', 'fire_size_bin_no'])

In [ ]:
# Remove loan status target from features data
target=df.medium_plus
y=target
#X = df.loc[:, df.columns !=target]
X=df.copy()
X=df.drop(columns=['medium_plus'])

# Split training/test datasets
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

# Create a StandardScaler instance
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [ ]:
model = RandomForestClassifier(n_estimators=100, random_state=78) 

#Fitting the model
model = model.fit(X_train, y_train)

# Making predictions using the testing data.
y_pred = model.predict(X_test)

In [ ]:
# Calculating the accuracy score.
rf_acc_score = balanced_accuracy_score(y_test, y_pred)
rf_acc_score

0.717443169278305

In [ ]:
# Calculating the confusion matrix
cm = confusion_matrix(y_test, y_pred)
cm_df = pd.DataFrame(
    cm, index=["Actual less than medium", "Actual medium plus"], columns=["Predicted less than medium", "Predicted medium +"])

In [ ]:
# Displaying Easy Ensemble Classifier
print("Random Forest Clasifier")
print("Confusion Matrix")
display(cm_df)
print(f"Accuracy Score : {rf_acc_score}")
print("Classification Report")
print(classification_report_imbalanced(y_test, y_pred))

Random Forest Clasifier
Confusion Matrix

                         Predicted less than medium  Predicted medium +
Actual less than medium                        2051                 249
Actual medium plus                              450                 535

Accuracy Score : 0.717443169278305
Classification Report
                   pre       rec       spe        f1       geo       iba       sup

          0       0.82      0.89      0.54      0.85      0.70      0.50      2300
          1       0.68      0.54      0.89      0.60      0.70      0.47       985

avg / total       0.78      0.79      0.65      0.78      0.70      0.49      3285

In [ ]:
#Calulate Feature Importances
importances = model.feature_importances_

In [ ]:
# We can sort the features by their importance.
sorted(zip(model.feature_importances_, X.columns), reverse=True)

[(0.31369372226484876, 'Hum_pre_7'),
 (0.2068841419307725, 'Temp_pre_7'),
 (0.19475608741212608, 'Wind_pre_7'),
 (0.17896801394957915, 'state_no'),
 (0.10569803444267352, 'discovery_month_no')]

----------------------------

--------------------------

### Balanced Random Forest Classifier

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import balanced_accuracy_score
from sklearn.preprocessing import OneHotEncoder
from pathlib import Path

from imblearn.ensemble import BalancedRandomForestClassifier


# Import our input dataset
data = Path('Resources_k/df7_k.csv')
df = pd.read_csv(data)
df

,fire_id,state_no,discovery_month_no,Temp_pre_7,Wind_pre_7,Hum_pre_7,fire_size_bin_no,medium_plus
0,3,29,6,18.142564,3.671282,35.353846,1,0
1,24,22,4,15.604790,1.775904,59.614458,3,0
2,31,25,4,-4.273834,6.658621,71.173116,1,0
3,35,8,10,18.188679,2.211429,60.328571,3,0
4,36,28,7,34.893333,3.695833,18.208333,5,1
...,...,...,...,...,...,...,...,...
13133,55336,39,8,28.719917,3.224274,55.426471,5,1
13134,55337,39,10,24.221869,1.563817,63.196819,5,1
13135,55341,33,9,10.734328,1.835821,67.266304,6,1
13136,55342,23,3,7.678571,3.803571,42.638384,5,1
13137,55343,10,10,15.732906,1.405983,56.257500,5,1

In [ ]:
df=df.drop(columns=['fire_id', 'fire_size_bin_no'])

In [ ]:
# Remove loan status target from features data
target=df.medium_plus
y=target
#X = df.loc[:, df.columns !=target]
X=df.copy()
X=df.drop(columns=['medium_plus'])

# Split training/test datasets
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

# Create a StandardScaler instance
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [ ]:
model = BalancedRandomForestClassifier(n_estimators=100, random_state=78) 

#Fitting the model
model = model.fit(X_train, y_train)

# Making predictions using the testing data.
y_pred = model.predict(X_test)

In [ ]:
# Calculating the accuracy score.
brf_acc_score = balanced_accuracy_score(y_test, y_pred)
brf_acc_score

0.7451909070845288

In [ ]:
# Calculating the confusion matrix
cm = confusion_matrix(y_test, y_pred)
cm_df = pd.DataFrame(
    cm, index=["Actual less than medium", "Actual medium plus"], columns=["Predicted less than medium", "Predicted medium +"])

In [ ]:
# Displaying Easy Ensemble Classifier
print("Balanced Random Forest Clasifier")
print("Confusion Matrix")
display(cm_df)
print(f"Accuracy Score : {brf_acc_score}")
print("Classification Report")
print(classification_report_imbalanced(y_test, y_pred))

Balanced Random Forest Clasifier
Confusion Matrix

                         Predicted less than medium  Predicted medium +
Actual less than medium                        1756                 544
Actual medium plus                              269                 716

Accuracy Score : 0.7451909070845288
Classification Report
                   pre       rec       spe        f1       geo       iba       sup

          0       0.87      0.76      0.73      0.81      0.74      0.56      2300
          1       0.57      0.73      0.76      0.64      0.74      0.55       985

avg / total       0.78      0.75      0.74      0.76      0.74      0.56      3285

-------------------------

----------------------------------

### Easy Ensemble Classifier

In [8]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import balanced_accuracy_score
from sklearn.preprocessing import OneHotEncoder
from pathlib import Path
from sklearn.preprocessing import StandardScaler
from imblearn.ensemble import EasyEnsembleClassifier

# Import our input dataset
data = Path('Resources_k/df7_k.csv')
df = pd.read_csv(data)
df

,fire_id,state_no,discovery_month_no,Temp_pre_7,Wind_pre_7,Hum_pre_7,fire_size_bin_no,medium_plus
0,3,29,6,18.142564,3.671282,35.353846,1,0
1,24,22,4,15.604790,1.775904,59.614458,3,0
2,31,25,4,-4.273834,6.658621,71.173116,1,0
3,35,8,10,18.188679,2.211429,60.328571,3,0
4,36,28,7,34.893333,3.695833,18.208333,5,1
...,...,...,...,...,...,...,...,...
13133,55336,39,8,28.719917,3.224274,55.426471,5,1
13134,55337,39,10,24.221869,1.563817,63.196819,5,1
13135,55341,33,9,10.734328,1.835821,67.266304,6,1
13136,55342,23,3,7.678571,3.803571,42.638384,5,1
13137,55343,10,10,15.732906,1.405983,56.257500,5,1

In [9]:
df=df.drop(columns=['fire_id', 'fire_size_bin_no'])

In [10]:
# Remove loan status target from features data
target=df.medium_plus
y=target
# X = df.loc[:, df.columns !=target]
X=df.drop(columns=['medium_plus']).values

# Split training/test datasets
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

# Create a StandardScaler instance
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [21]:
X_test_scaled

array([[ 1.49691652,  0.33288158,  1.81061152,  0.42225824, -2.42711523],
       [ 1.79469202, -0.79577714, -1.3073249 ,  0.76553512,  1.30590304],
       [-1.10861914,  0.70910116,  0.41341934, -0.78454843,  1.48544833],
       ...,
       [ 1.19914102,  2.21397946, -0.74605266, -0.17139494,  0.16396625],
       [-1.10861914,  0.33288158, -0.22001741,  0.53030658,  1.40623668],
       [-0.88528751,  1.46154031,  0.3632356 , -0.90650679,  0.68645195]])

In [ ]:
x

In [11]:
# Train the EasyEnsembleClassifier

model = EasyEnsembleClassifier(n_estimators=10, random_state=78) 

#Fitting the model
model = model.fit(X_train, y_train)

# Making predictions using the testing data.
y_pred = model.predict(X_test)

In [12]:
# Calculated the balanced accuracy score
ee_acc_score = balanced_accuracy_score(y_test, y_pred)
ee_acc_score

0.7576531728665208

In [13]:
# Calculating the confusion matrix
cm = confusion_matrix(y_test, y_pred)
cm_df = pd.DataFrame(
    cm, index=["Actual less than medium", "Actual medium plus"], columns=["Predicted less than medium", "Predicted medium +"])

In [14]:
# Displaying Easy Ensemble Classifier
print("Easy Ensemble Classifier")
print("Confusion Matrix")
display(cm_df)
print(f"Accuracy Score : {ee_acc_score}")
print("Classification Report")
print(classification_report_imbalanced(y_test, y_pred))

Easy Ensemble Classifier
Confusion Matrix

                         Predicted less than medium  Predicted medium +
Actual less than medium                        1783                 502
Actual medium plus                              265                 735

Accuracy Score : 0.7576531728665208
Classification Report
                   pre       rec       spe        f1       geo       iba       sup

          0       0.87      0.78      0.73      0.82      0.76      0.58      2285
          1       0.59      0.73      0.78      0.66      0.76      0.57      1000

avg / total       0.79      0.77      0.75      0.77      0.76      0.57      3285

In [16]:
import joblib
joblib.dump(model, 'model_joblib_ee')
joblib.load('model_joblib_ee')

EasyEnsembleClassifier(random_state=78)

--------------------------------------

---------------------------

### Naive Random Oversampling

In [ ]:
# Import our input dataset
data = Path('Resources_k/df7_k.csv')
df = pd.read_csv(data)
df

,fire_id,state_no,discovery_month_no,Temp_pre_7,Wind_pre_7,Hum_pre_7,fire_size_bin_no,medium_plus
0,3,29,6,18.142564,3.671282,35.353846,1,0
1,24,22,4,15.604790,1.775904,59.614458,3,0
2,31,25,4,-4.273834,6.658621,71.173116,1,0
3,35,8,10,18.188679,2.211429,60.328571,3,0
4,36,28,7,34.893333,3.695833,18.208333,5,1
...,...,...,...,...,...,...,...,...
13133,55336,39,8,28.719917,3.224274,55.426471,5,1
13134,55337,39,10,24.221869,1.563817,63.196819,5,1
13135,55341,33,9,10.734328,1.835821,67.266304,6,1
13136,55342,23,3,7.678571,3.803571,42.638384,5,1
13137,55343,10,10,15.732906,1.405983,56.257500,5,1

In [ ]:
df=df.drop(columns=['fire_id', 'fire_size_bin_no'])

In [ ]:
# Remove loan status target from features data
target=df.medium_plus
y=target
# X = df.loc[:, df.columns !=target]
X=df.drop(columns=['medium_plus']).values

# Split training/test datasets
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

# Create a StandardScaler instance
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [ ]:
import warnings
warnings.filterwarnings('ignore')

from collections import Counter

# implement random oversampling
from imblearn.over_sampling import RandomOverSampler
ros = RandomOverSampler(random_state=1)
X_resampled, y_resampled = ros.fit_resample(X_train, y_train)

Counter(y_resampled)

Counter({0: 6979, 1: 6979})

In [ ]:
# Logistic regression using random oversampled data
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(solver='lbfgs', random_state=1)
model.fit(X_resampled, y_resampled)

LogisticRegression(random_state=1)

In [ ]:
# Calculated the balanced accuracy score
from sklearn.metrics import balanced_accuracy_score
y_pred = model.predict(X_test)
nr_acc_score= balanced_accuracy_score(y_test, y_pred)

In [ ]:
# Calculating the confusion matrix
cm = confusion_matrix(y_test, y_pred)
cm_df = pd.DataFrame(
    cm, index=["Actual less than medium", "Actual medium plus"], columns=["Predicted less than medium", "Predicted medium +"])

In [ ]:
# Displaying Random Oversampling results
print("Naive Random Oversampling")
print("Confusion Matrix")
display(cm_df)
print(f"Accuracy Score : {nr_acc_score}")
print("Classification Report")
print(classification_report_imbalanced(y_test, y_pred))

Naive Random Oversampling
Confusion Matrix

                         Predicted less than medium  Predicted medium +
Actual less than medium                        1667                 618
Actual medium plus                              315                 685

Accuracy Score : 0.7072702407002188
Classification Report
                   pre       rec       spe        f1       geo       iba       sup

          0       0.84      0.73      0.69      0.78      0.71      0.50      2285
          1       0.53      0.69      0.73      0.59      0.71      0.50      1000

avg / total       0.75      0.72      0.70      0.72      0.71      0.50      3285

### SMOTE Oversampling

In [ ]:
# Import our input dataset
data = Path('Resources_k/df7_k.csv')
df = pd.read_csv(data)
df

,fire_id,state_no,discovery_month_no,Temp_pre_7,Wind_pre_7,Hum_pre_7,fire_size_bin_no,medium_plus
0,3,29,6,18.142564,3.671282,35.353846,1,0
1,24,22,4,15.604790,1.775904,59.614458,3,0
2,31,25,4,-4.273834,6.658621,71.173116,1,0
3,35,8,10,18.188679,2.211429,60.328571,3,0
4,36,28,7,34.893333,3.695833,18.208333,5,1
...,...,...,...,...,...,...,...,...
13133,55336,39,8,28.719917,3.224274,55.426471,5,1
13134,55337,39,10,24.221869,1.563817,63.196819,5,1
13135,55341,33,9,10.734328,1.835821,67.266304,6,1
13136,55342,23,3,7.678571,3.803571,42.638384,5,1
13137,55343,10,10,15.732906,1.405983,56.257500,5,1

In [ ]:
df=df.drop(columns=['fire_id', 'fire_size_bin_no'])

In [ ]:
# Remove loan status target from features data
target=df.medium_plus
y=target
# X = df.loc[:, df.columns !=target]
X=df.drop(columns=['medium_plus']).values

# Split training/test datasets
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

# Create a StandardScaler instance
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [ ]:
# Resample the training data with SMOTE
from imblearn.over_sampling import SMOTE
X_resampled, y_resampled = SMOTE(random_state=1, sampling_strategy='auto').fit_resample(
    X_train, y_train
)
Counter(y_resampled)

Counter({0: 6979, 1: 6979})

In [ ]:
# Train the Logistic Regression model using the resampled data
model = LogisticRegression(solver='lbfgs', random_state=1)
model.fit(X_resampled, y_resampled)

LogisticRegression(random_state=1)

In [ ]:
# Calculated the balanced accuracy score
from sklearn.metrics import balanced_accuracy_score
y_pred = model.predict(X_test)
smote_acc_score=balanced_accuracy_score(y_test, y_pred)

In [ ]:
# Calculating the confusion matrix
cm = confusion_matrix(y_test, y_pred)
cm_df = pd.DataFrame(
    cm, index=["Actual less than medium", "Actual medium plus"], columns=["Predicted less than medium", "Predicted medium +"])

In [ ]:
# Displaying SMOTE results
print("SMOTE Oversampling")
print("Confusion Matrix")
display(cm_df)
print(f"Accuracy Score : {smote_acc_score}")
print("Classification Report")
print(classification_report_imbalanced(y_test, y_pred))

SMOTE Oversampling
Confusion Matrix

                         Predicted less than medium  Predicted medium +
Actual less than medium                        1684                 601
Actual medium plus                              328                 672

Accuracy Score : 0.7044901531728666
Classification Report
                   pre       rec       spe        f1       geo       iba       sup

          0       0.84      0.74      0.67      0.78      0.70      0.50      2285
          1       0.53      0.67      0.74      0.59      0.70      0.49      1000

avg / total       0.74      0.72      0.69      0.73      0.70      0.50      3285

## Undersampling

In [ ]:
# Import our input dataset
data = Path('Resources_k/df7_k.csv')
df = pd.read_csv(data)
df

,fire_id,state_no,discovery_month_no,Temp_pre_7,Wind_pre_7,Hum_pre_7,fire_size_bin_no,medium_plus
0,3,29,6,18.142564,3.671282,35.353846,1,0
1,24,22,4,15.604790,1.775904,59.614458,3,0
2,31,25,4,-4.273834,6.658621,71.173116,1,0
3,35,8,10,18.188679,2.211429,60.328571,3,0
4,36,28,7,34.893333,3.695833,18.208333,5,1
...,...,...,...,...,...,...,...,...
13133,55336,39,8,28.719917,3.224274,55.426471,5,1
13134,55337,39,10,24.221869,1.563817,63.196819,5,1
13135,55341,33,9,10.734328,1.835821,67.266304,6,1
13136,55342,23,3,7.678571,3.803571,42.638384,5,1
13137,55343,10,10,15.732906,1.405983,56.257500,5,1

In [ ]:
df=df.drop(columns=['fire_id', 'fire_size_bin_no'])

In [ ]:
# Remove loan status target from features data
target=df.medium_plus
y=target
# X = df.loc[:, df.columns !=target]
X=df.drop(columns=['medium_plus']).values

# Split training/test datasets
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

# Create a StandardScaler instance
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [ ]:
# Resample the data using the ClusterCentroids resampler
from imblearn.under_sampling import ClusterCentroids
cc = ClusterCentroids(random_state=1)
X_resampled, y_resampled = cc.fit_resample(X_train, y_train)
Counter(y_resampled)

Counter({0: 2874, 1: 2874})

In [ ]:
# Train the Logistic Regression model using the resampled data
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(solver='lbfgs', random_state=1)
model.fit(X_resampled, y_resampled)

LogisticRegression(random_state=1)

In [ ]:
# Calculated the balanced accuracy score
from sklearn.metrics import balanced_accuracy_score
y_pred = model.predict(X_test)
cc_acc_score= balanced_accuracy_score(y_test, y_pred)

In [ ]:
# Calculating the confusion matrix
cm = confusion_matrix(y_test, y_pred)
cm_df = pd.DataFrame(
    cm, index=["Actual less than medium", "Actual medium plus"], columns=["Predicted less than medium", "Predicted medium +"])

In [ ]:
# Displaying Undersampling results
print("Cluster Centroid Undersampling")
print("Confusion Matrix")
display(cm_df)
print(f"Accuracy Score : {cc_acc_score}")
print("Classification Report")
print(classification_report_imbalanced(y_test, y_pred))

Cluster Centroid Undersampling
Confusion Matrix

                         Predicted less than medium  Predicted medium +
Actual less than medium                        1655                 630
Actual medium plus                              334                 666

Accuracy Score : 0.6951444201312911
Classification Report
                   pre       rec       spe        f1       geo       iba       sup

          0       0.83      0.72      0.67      0.77      0.69      0.49      2285
          1       0.51      0.67      0.72      0.58      0.69      0.48      1000

avg / total       0.74      0.71      0.68      0.72      0.69      0.48      3285

## Combination (Over and Under) Sampling

In [ ]:
# Import our input dataset
data = Path('Resources_k/df7_k.csv')
df = pd.read_csv(data)
df

,fire_id,state_no,discovery_month_no,Temp_pre_7,Wind_pre_7,Hum_pre_7,fire_size_bin_no,medium_plus
0,3,29,6,18.142564,3.671282,35.353846,1,0
1,24,22,4,15.604790,1.775904,59.614458,3,0
2,31,25,4,-4.273834,6.658621,71.173116,1,0
3,35,8,10,18.188679,2.211429,60.328571,3,0
4,36,28,7,34.893333,3.695833,18.208333,5,1
...,...,...,...,...,...,...,...,...
13133,55336,39,8,28.719917,3.224274,55.426471,5,1
13134,55337,39,10,24.221869,1.563817,63.196819,5,1
13135,55341,33,9,10.734328,1.835821,67.266304,6,1
13136,55342,23,3,7.678571,3.803571,42.638384,5,1
13137,55343,10,10,15.732906,1.405983,56.257500,5,1

In [ ]:
df=df.drop(columns=['fire_id', 'fire_size_bin_no'])

In [ ]:
# Remove loan status target from features data
target=df.medium_plus
y=target
# X = df.loc[:, df.columns !=target]
X=df.drop(columns=['medium_plus']).values

# Split training/test datasets
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

# Create a StandardScaler instance
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [ ]:
# Resample the training data with SMOTEENN
# Warning: This is a large dataset, and this step may take some time to complete
from imblearn.combine import SMOTEENN

smote_enn = SMOTEENN(random_state=1)
X_resampled, y_resampled = smote_enn.fit_resample(X, y)
Counter(y_resampled)

Counter({0: 5216, 1: 6428})

In [ ]:
# Train the Logistic Regression model using the resampled data
from imblearn.ensemble import EasyEnsembleClassifier
model = EasyEnsembleClassifier(n_estimators=100, random_state=78) 
model.fit(X_resampled, y_resampled)

EasyEnsembleClassifier(n_estimators=100, random_state=78)

In [ ]:
# Calculated the balanced accuracy score
from sklearn.metrics import balanced_accuracy_score
y_pred = model.predict(X_test)
smoteenn_acc_score = balanced_accuracy_score(y_test, y_pred)

In [ ]:
# Calculating the confusion matrix
cm = confusion_matrix(y_test, y_pred)
cm_df = pd.DataFrame(
    cm, index=["Actual less than medium", "Actual medium plus"], columns=["Predicted less than medium", "Predicted medium +"])

In [ ]:
# Displaying SMOTEEN results
print("SMOTEENN Sampling")
print("Confusion Matrix")
display(cm_df)
print(f"Accuracy Score : {smoteenn_acc_score}")
print("Classification Report")
print(classification_report_imbalanced(y_test, y_pred))

SMOTEENN Sampling
Confusion Matrix

                         Predicted less than medium  Predicted medium +
Actual less than medium                        1741                 544
Actual medium plus                              243                 757

Accuracy Score : 0.7594628008752735
Classification Report
                   pre       rec       spe        f1       geo       iba       sup

          0       0.88      0.76      0.76      0.82      0.76      0.58      2285
          1       0.58      0.76      0.76      0.66      0.76      0.58      1000

avg / total       0.79      0.76      0.76      0.77      0.76      0.58      3285

---------------------------------

--------------------------------

### Gradient Boosting Classifier

In [ ]:
import pandas as pd
from pathlib import Path
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import balanced_accuracy_score
from sklearn.preprocessing import OneHotEncoder
import pandas as pd

In [ ]:
# Import our input dataset
data = Path('Resources_k/df7_k.csv')
df = pd.read_csv(data)
df

,fire_id,state_no,discovery_month_no,Temp_pre_7,Wind_pre_7,Hum_pre_7,fire_size_bin_no,medium_plus
0,3,29,6,18.142564,3.671282,35.353846,1,0
1,24,22,4,15.604790,1.775904,59.614458,3,0
2,31,25,4,-4.273834,6.658621,71.173116,1,0
3,35,8,10,18.188679,2.211429,60.328571,3,0
4,36,28,7,34.893333,3.695833,18.208333,5,1
...,...,...,...,...,...,...,...,...
13133,55336,39,8,28.719917,3.224274,55.426471,5,1
13134,55337,39,10,24.221869,1.563817,63.196819,5,1
13135,55341,33,9,10.734328,1.835821,67.266304,6,1
13136,55342,23,3,7.678571,3.803571,42.638384,5,1
13137,55343,10,10,15.732906,1.405983,56.257500,5,1

In [ ]:
df=df.drop(columns=['fire_id', 'fire_size_bin_no'])

In [ ]:
# Remove loan status target from features data
target=df.medium_plus
y=target
# X = df.loc[:, df.columns !=target]
X=df.drop(columns=['medium_plus']).values

# Split training/test datasets
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

# Create a StandardScaler instance
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

  ### Choose best learning rate

In [ ]:
from sklearn.ensemble import GradientBoostingClassifier

# Create a classifier object
learning_rates = [0.05, 0.1, 0.25, 0.5, 0.75, 1]
for learning_rate in learning_rates:
    classifier = GradientBoostingClassifier(n_estimators=10,
                                            learning_rate=learning_rate,
                                            max_features='auto',
                                            max_depth=3,
                                            random_state=1)

    # Fit the model
    classifier.fit(X_train_scaled, y_train)
    print("Learning rate: ", learning_rate)

    # Score the model
    print("Accuracy score (training): {0:.3f}".format(
        classifier.score(
            X_train_scaled,
            y_train)))
    print("Accuracy score (validation): {0:.3f}".format(
        classifier.score(
            X_test_scaled,
            y_test)))
    print()

Learning rate:  0.05
Accuracy score (training): 0.736
Accuracy score (validation): 0.722

Learning rate:  0.1
Accuracy score (training): 0.779
Accuracy score (validation): 0.770

Learning rate:  0.25
Accuracy score (training): 0.802
Accuracy score (validation): 0.781

Learning rate:  0.5
Accuracy score (training): 0.802
Accuracy score (validation): 0.787

Learning rate:  0.75
Accuracy score (training): 0.808
Accuracy score (validation): 0.782

Learning rate:  1
Accuracy score (training): 0.809
Accuracy score (validation): 0.786

  ### Create Gradient Boosting Classifier

In [ ]:
# Choose a learning rate and create classifier
classifier = GradientBoostingClassifier(n_estimators=100,
                                        learning_rate=0.1,
                                        max_features='auto',
                                        max_depth=3,
                                        random_state=1)

# Fit the model
classifier.fit(X_train_scaled, y_train)

# Make Prediction
predictions = classifier.predict(X_test_scaled)
pd.DataFrame({"Prediction": predictions, "Actual": y_test}).head(20)

       Prediction  Actual
4841            1       0
3257            0       0
3796            0       0
5376            0       0
142             0       0
3013            0       0
12112           0       1
6822            0       0
9282            0       0
7166            0       0
1804            0       0
7068            0       0
10206           0       1
4405            0       1
8940            1       1
5151            0       0
12777           0       1
994             1       1
943             1       0
1131            0       1

  ### Evaluate the model

In [ ]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import classification_report
# Calculating the accuracy score
gb_acc_score = balanced_accuracy_score(y_test, predictions)
print(f"Accuracy Score : {gb_acc_score}")

Accuracy Score : 0.7292002188183807

In [ ]:
# Calculating the confusion matrix
cm = confusion_matrix(y_test, y_pred)
cm_df = pd.DataFrame(
    cm, index=["Actual less than medium", "Actual medium plus"], columns=["Predicted less than medium", "Predicted medium +"])

In [ ]:
# Displaying SMOTEEN results
print("Gradient Boosting Sampling")
print("Confusion Matrix")
display(cm_df)
print(f"Accuracy Score : {gb_acc_score}")
print("Classification Report")
print(classification_report_imbalanced(y_test, y_pred))

Gradient Boosting Sampling
Confusion Matrix

                         Predicted less than medium  Predicted medium +
Actual less than medium                        1741                 544
Actual medium plus                              243                 757

Accuracy Score : 0.7292002188183807
Classification Report
                   pre       rec       spe        f1       geo       iba       sup

          0       0.88      0.76      0.76      0.82      0.76      0.58      2285
          1       0.58      0.76      0.76      0.66      0.76      0.58      1000

avg / total       0.79      0.76      0.76      0.77      0.76      0.58      3285

---------------------------------

-----------------------

### Logistic Regression

In [ ]:
import pandas as pd
from pathlib import Path
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import balanced_accuracy_score
from sklearn.preprocessing import OneHotEncoder
import pandas as pd

In [ ]:
# Import our input dataset
data = Path('Resources_k/df7_k.csv')
df = pd.read_csv(data)
df.head()

,fire_id,state_no,discovery_month_no,Temp_pre_7,Wind_pre_7,Hum_pre_7,fire_size_bin_no,medium_plus
0,3,29,6,18.142564,3.671282,35.353846,1,0
1,24,22,4,15.604790,1.775904,59.614458,3,0
2,31,25,4,-4.273834,6.658621,71.173116,1,0
3,35,8,10,18.188679,2.211429,60.328571,3,0
4,36,28,7,34.893333,3.695833,18.208333,5,1

In [ ]:
df=df.drop(columns=["fire_id", 'fire_size_bin_no'])

# Generate our categorical variable list
#cat = df.dtypes[df.dtypes == "object"].index.tolist()
#cat=['discovery_month', 'state']

# Check the number of unique values in each column
#df[cat].nunique()
df

,state_no,discovery_month_no,Temp_pre_7,Wind_pre_7,Hum_pre_7,medium_plus
0,29,6,18.142564,3.671282,35.353846,0
1,22,4,15.604790,1.775904,59.614458,0
2,25,4,-4.273834,6.658621,71.173116,0
3,8,10,18.188679,2.211429,60.328571,0
4,28,7,34.893333,3.695833,18.208333,1
...,...,...,...,...,...,...
13133,39,8,28.719917,3.224274,55.426471,1
13134,39,10,24.221869,1.563817,63.196819,1
13135,33,9,10.734328,1.835821,67.266304,1
13136,23,3,7.678571,3.803571,42.638384,1
13137,10,10,15.732906,1.405983,56.257500,1

In [ ]:
# Remove loan status target from features data
target=df.medium_plus
y=target
# X = df.loc[:, df.columns !=target]
X=df.drop(columns=["medium_plus"]).values

# Split training/test datasets
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

# Create a StandardScaler instance
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [ ]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(solver='lbfgs',
                                max_iter=200,
                                random_state=78)

In [ ]:
classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)
results = pd.DataFrame({"Prediction": y_pred, "Actual": y_test}).reset_index(drop=True)
results.head(20)

    Prediction  Actual
0            0       1
1            0       1
2            0       0
3            0       0
4            0       0
5            0       0
6            0       1
7            1       1
8            1       1
9            0       0
10           0       0
11           0       0
12           0       0
13           1       1
14           1       1
15           0       0
16           0       0
17           0       0
18           0       0
19           0       0

In [ ]:
from sklearn.metrics import accuracy_score
log_acc_score=balanced_accuracy_score(y_test, y_pred)
log_acc_score

0.6138148311630987

In [ ]:
print(f'Supervised Machine Learning Models Using Label Encoder')
print(f"Neural Networking Accuracy: {model_accuracy}")
print(f"Random Forest Accuracy Score : {rf_acc_score}")
print(f"Balanced Random Forest Accuracy Score : {brf_acc_score}")
print(f"Easy Ensemble Accuracy Score : {ee_acc_score}")
print(f"Naive Random Oversampling Accuracy Score : {nr_acc_score}")
print(f"SMOTE Oversampling Accuracy Score : {smote_acc_score}")
print(f"Centroid Clustering Undersampling Accuracy Score : {cc_acc_score}")
print(f"SMOTEENN Over/Undersampling Accuracy Score : {smoteenn_acc_score}")
print(f"Gradient Boosting Accuracy Score : {gb_acc_score}")
print(f"Logistic Regression Accuracy Score : {log_acc_score}")

Supervised Machine Learning Models Using Label Encoder
Neural Networking Accuracy: 0.7001522183418274
Random Forest Accuracy Score : 0.717443169278305
Balanced Random Forest Accuracy Score : 0.7451909070845288
Easy Ensemble Accuracy Score : 0.7580284463894967
Naive Random Oversampling Accuracy Score : 0.7072702407002188
SMOTE Oversampling Accuracy Score : 0.7044901531728666
Centroid Clustering Undersampling Accuracy Score : 0.6951444201312911
SMOTEENN Over/Undersampling Accuracy Score : 0.7594628008752735
Gradient Boosting Accuracy Score : 0.7292002188183807
Logistic Regression Accuracy Score : 0.6138148311630987