In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("Resources/Original Data/FW_Veg_Rem_Combined_ORIGINAL.csv",index_col=False)
df

,Unnamed: 0,Unnamed: 0.1,fire_name,fire_size,fire_size_class,stat_cause_descr,latitude,longitude,state,disc_clean_date,...,Wind_cont,Hum_pre_30,Hum_pre_15,Hum_pre_7,Hum_cont,Prec_pre_30,Prec_pre_15,Prec_pre_7,Prec_cont,remoteness
0,0,0,NaN,10.0,C,Missing/Undefined,18.105072,-66.753044,PR,2/11/2007,...,3.250413,78.216590,76.793750,76.381579,78.724370,0.0,0.0,0.0,0.0,0.017923
1,1,1,NaN,3.0,B,Arson,35.038330,-87.610000,TN,12/11/2006,...,2.122320,70.840000,65.858911,55.505882,81.682678,59.8,8.4,0.0,86.8,0.184355
2,2,2,NaN,60.0,C,Arson,34.947800,-88.722500,MS,2/29/2004,...,3.369050,75.531629,75.868613,76.812834,65.063800,168.8,42.2,18.1,124.5,0.194544
3,3,3,WNA 1,1.0,B,Debris Burning,39.641400,-119.308300,NV,6/6/2005,...,0.000000,44.778429,37.140811,35.353846,0.000000,10.4,7.2,0.0,0.0,0.487447
4,4,4,NaN,2.0,B,Miscellaneous,30.700600,-90.591400,LA,9/22/1999,...,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.0,-1.0,-1.0,-1.0,0.214633
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55362,55362,55362,IMPACT,6289.0,G,Missing/Undefined,39.180000,-96.784167,KS,10/15/2015,...,3.804803,65.671410,61.839572,54.625698,55.042092,35.4,8.2,0.0,249.0,0.331501
55363,55363,55363,BUTTE,70868.0,G,Missing/Undefined,38.342719,-120.695967,CA,9/9/2015,...,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.0,-1.0,-1.0,-1.0,0.124683
55364,55364,55364,WILLOW,5702.0,G,Arson,37.262607,-119.511139,CA,7/25/2015,...,2.529158,43.755556,43.755556,44.443975,35.924406,0.0,0.0,0.0,0.0,0.097682
55365,55365,55365,BARKER,3261.0,F,Miscellaneous,40.604300,-123.080450,CA,7/31/2015,...,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.0,-1.0,-1.0,-1.0,0.178206
55366,55366,55366,VALLEY,76067.0,G,Missing/Undefined,38.843988,-122.759707,CA,9/12/2015,...,1.208073,50.521912,46.310627,37.178571,58.063802,0.3,0.3,0.0,18.8,0.167305

In [3]:
df.columns

Index(['Unnamed: 0', 'Unnamed: 0.1', 'fire_name', 'fire_size',
       'fire_size_class', 'stat_cause_descr', 'latitude', 'longitude', 'state',
       'disc_clean_date', 'cont_clean_date', 'discovery_month',
       'disc_date_final', 'cont_date_final', 'putout_time', 'disc_date_pre',
       'disc_pre_year', 'disc_pre_month', 'wstation_usaf', 'dstation_m',
       'wstation_wban', 'wstation_byear', 'wstation_eyear', 'Vegetation',
       'fire_mag', 'weather_file', 'Temp_pre_30', 'Temp_pre_15', 'Temp_pre_7',
       'Temp_cont', 'Wind_pre_30', 'Wind_pre_15', 'Wind_pre_7', 'Wind_cont',
       'Hum_pre_30', 'Hum_pre_15', 'Hum_pre_7', 'Hum_cont', 'Prec_pre_30',
       'Prec_pre_15', 'Prec_pre_7', 'Prec_cont', 'remoteness'],
      dtype='object')

In [4]:
df=df.dropna()
df

,Unnamed: 0,Unnamed: 0.1,fire_name,fire_size,fire_size_class,stat_cause_descr,latitude,longitude,state,disc_clean_date,...,Wind_cont,Hum_pre_30,Hum_pre_15,Hum_pre_7,Hum_cont,Prec_pre_30,Prec_pre_15,Prec_pre_7,Prec_cont,remoteness
3,3,3,WNA 1,1.00,B,Debris Burning,39.641400,-119.308300,NV,6/6/2005,...,0.000000,44.778429,37.140811,35.353846,0.000000,10.4,7.2,0.0,0.0,0.487447
9,9,9,CRAZY,1.00,B,Miscellaneous,48.839400,-99.718500,ND,4/19/2004,...,0.000000,64.606509,55.943038,54.337838,0.000000,12.3,1.8,0.0,0.0,0.291683
26,26,26,STO3573155,2.00,B,Debris Burning,35.718900,-92.335000,AR,1/19/2014,...,0.000000,76.091398,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.227270
31,31,31,AXE RONDEAU,1.20,B,Debris Burning,48.833000,-99.783600,ND,4/7/2007,...,0.000000,77.575012,75.963981,71.173116,0.000000,21.2,21.2,9.2,0.0,0.292303
35,35,35,FY2001-EARLY-021,30.18,C,Debris Burning,31.259000,-84.895600,GA,10/19/2000,...,0.000000,67.551783,61.733788,60.328571,0.000000,0.0,0.0,0.0,0.0,0.162416
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55349,55349,55349,BROWN RANCH,17831.00,G,Miscellaneous,30.005000,-100.391167,TX,8/10/2015,...,2.360093,60.470917,56.987013,58.615538,58.243619,0.0,0.0,0.0,0.0,0.451149
55350,55350,55350,PRICKLEY PEAR,3452.00,F,Miscellaneous,30.400883,-101.331933,TX,8/28/2015,...,3.082979,44.411268,47.176638,47.944785,39.510638,4.6,4.6,0.0,0.0,0.429604
55351,55351,55351,COTTONWOOD GULCH,8300.00,G,Miscellaneous,45.922100,-111.422500,MT,10/11/2015,...,3.367769,60.914780,62.120643,66.795455,48.628099,15.8,2.8,2.8,0.0,0.009711
55363,55363,55363,BUTTE,70868.00,G,Missing/Undefined,38.342719,-120.695967,CA,9/9/2015,...,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.0,-1.0,-1.0,-1.0,0.124683
55365,55365,55365,BARKER,3261.00,F,Miscellaneous,40.604300,-123.080450,CA,7/31/2015,...,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.0,-1.0,-1.0,-1.0,0.178206

In [5]:
df_new=df[['fire_name', 'fire_size',
       'fire_size_class', 'stat_cause_descr', 'latitude', 'longitude', 'state',
       'disc_clean_date', 'cont_clean_date', 'discovery_month',
       'putout_time',  'Vegetation','fire_mag', 'Temp_pre_30', 'Temp_pre_15', 'Temp_pre_7',
       'Temp_cont', 'Wind_pre_30', 'Wind_pre_15', 'Wind_pre_7', 'Wind_cont',
       'Hum_pre_30', 'Hum_pre_15', 'Hum_pre_7', 'Hum_cont', 'Prec_pre_30',
       'Prec_pre_15', 'Prec_pre_7', 'Prec_cont', 'remoteness']]
df_new

,fire_name,fire_size,fire_size_class,stat_cause_descr,latitude,longitude,state,disc_clean_date,cont_clean_date,discovery_month,...,Wind_cont,Hum_pre_30,Hum_pre_15,Hum_pre_7,Hum_cont,Prec_pre_30,Prec_pre_15,Prec_pre_7,Prec_cont,remoteness
3,WNA 1,1.00,B,Debris Burning,39.641400,-119.308300,NV,6/6/2005,6/6/2005,Jun,...,0.000000,44.778429,37.140811,35.353846,0.000000,10.4,7.2,0.0,0.0,0.487447
9,CRAZY,1.00,B,Miscellaneous,48.839400,-99.718500,ND,4/19/2004,4/19/2004,Apr,...,0.000000,64.606509,55.943038,54.337838,0.000000,12.3,1.8,0.0,0.0,0.291683
26,STO3573155,2.00,B,Debris Burning,35.718900,-92.335000,AR,1/19/2014,1/19/2014,Jan,...,0.000000,76.091398,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.227270
31,AXE RONDEAU,1.20,B,Debris Burning,48.833000,-99.783600,ND,4/7/2007,4/7/2007,Apr,...,0.000000,77.575012,75.963981,71.173116,0.000000,21.2,21.2,9.2,0.0,0.292303
35,FY2001-EARLY-021,30.18,C,Debris Burning,31.259000,-84.895600,GA,10/19/2000,10/19/2000,Oct,...,0.000000,67.551783,61.733788,60.328571,0.000000,0.0,0.0,0.0,0.0,0.162416
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55349,BROWN RANCH,17831.00,G,Miscellaneous,30.005000,-100.391167,TX,8/10/2015,8/16/2015,Aug,...,2.360093,60.470917,56.987013,58.615538,58.243619,0.0,0.0,0.0,0.0,0.451149
55350,PRICKLEY PEAR,3452.00,F,Miscellaneous,30.400883,-101.331933,TX,8/28/2015,8/30/2015,Aug,...,3.082979,44.411268,47.176638,47.944785,39.510638,4.6,4.6,0.0,0.0,0.429604
55351,COTTONWOOD GULCH,8300.00,G,Miscellaneous,45.922100,-111.422500,MT,10/11/2015,10/16/2015,Oct,...,3.367769,60.914780,62.120643,66.795455,48.628099,15.8,2.8,2.8,0.0,0.009711
55363,BUTTE,70868.00,G,Missing/Undefined,38.342719,-120.695967,CA,9/9/2015,10/1/2015,Sep,...,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.0,-1.0,-1.0,-1.0,0.124683
55365,BARKER,3261.00,F,Miscellaneous,40.604300,-123.080450,CA,7/31/2015,9/12/2015,Jul,...,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.0,-1.0,-1.0,-1.0,0.178206

In [6]:
df_new['disc_clean_date'] = pd.to_datetime(df_new['disc_clean_date'].str.strip(), format='%m/%d/%Y')
df_new['year'] = df_new.disc_clean_date.dt.year

C:\Users\KATLIN\AppData\Local\Temp/ipykernel_24876/216051678.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new['disc_clean_date'] = pd.to_datetime(df_new['disc_clean_date'].str.strip(), format='%m/%d/%Y')
C:\Users\KATLIN\AppData\Local\Temp/ipykernel_24876/216051678.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new['year'] = df_new.disc_clean_date.dt.year

In [7]:
df_new= df_new[df_new.Temp_pre_30 != -1.0]
df_new

,fire_name,fire_size,fire_size_class,stat_cause_descr,latitude,longitude,state,disc_clean_date,cont_clean_date,discovery_month,...,Hum_pre_30,Hum_pre_15,Hum_pre_7,Hum_cont,Prec_pre_30,Prec_pre_15,Prec_pre_7,Prec_cont,remoteness,year
3,WNA 1,1.00,B,Debris Burning,39.641400,-119.308300,NV,2005-06-06,6/6/2005,Jun,...,44.778429,37.140811,35.353846,0.000000,10.4,7.2,0.0,0.0,0.487447,2005
9,CRAZY,1.00,B,Miscellaneous,48.839400,-99.718500,ND,2004-04-19,4/19/2004,Apr,...,64.606509,55.943038,54.337838,0.000000,12.3,1.8,0.0,0.0,0.291683,2004
26,STO3573155,2.00,B,Debris Burning,35.718900,-92.335000,AR,2014-01-19,1/19/2014,Jan,...,76.091398,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.227270,2014
31,AXE RONDEAU,1.20,B,Debris Burning,48.833000,-99.783600,ND,2007-04-07,4/7/2007,Apr,...,77.575012,75.963981,71.173116,0.000000,21.2,21.2,9.2,0.0,0.292303,2007
35,FY2001-EARLY-021,30.18,C,Debris Burning,31.259000,-84.895600,GA,2000-10-19,10/19/2000,Oct,...,67.551783,61.733788,60.328571,0.000000,0.0,0.0,0.0,0.0,0.162416,2000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55342,PINECREST,5086.00,G,Debris Burning,45.656100,-109.114200,MT,2015-03-28,4/2/2015,Mar,...,51.676681,46.933399,42.638384,28.844444,0.0,0.0,0.0,0.0,0.046649,2015
55343,WALKER,5963.00,G,Debris Burning,43.785671,-115.985922,ID,2015-10-10,10/20/2015,Oct,...,51.541802,53.945191,56.257500,49.915194,0.0,0.0,0.0,0.0,0.060013,2015
55349,BROWN RANCH,17831.00,G,Miscellaneous,30.005000,-100.391167,TX,2015-08-10,8/16/2015,Aug,...,60.470917,56.987013,58.615538,58.243619,0.0,0.0,0.0,0.0,0.451149,2015
55350,PRICKLEY PEAR,3452.00,F,Miscellaneous,30.400883,-101.331933,TX,2015-08-28,8/30/2015,Aug,...,44.411268,47.176638,47.944785,39.510638,4.6,4.6,0.0,0.0,0.429604,2015
55351,COTTONWOOD GULCH,8300.00,G,Miscellaneous,45.922100,-111.422500,MT,2015-10-11,10/16/2015,Oct,...,60.914780,62.120643,66.795455,48.628099,15.8,2.8,2.8,0.0,0.009711,2015

In [8]:
df_new.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 13752 entries, 3 to 55351
Data columns (total 31 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   fire_name         13752 non-null  object
 1   fire_size         13752 non-null  float64
 2   fire_size_class   13752 non-null  object
 3   stat_cause_descr  13752 non-null  object
 4   latitude          13752 non-null  float64
 5   longitude         13752 non-null  float64
 6   state             13752 non-null  object
 7   disc_clean_date   13752 non-null  datetime64[ns]
 8   cont_clean_date   13752 non-null  object
 9   discovery_month   13752 non-null  object
 10  putout_time       13752 non-null  object
 11  Vegetation        13752 non-null  int64
 12  fire_mag          13752 non-null  float64
 13  Temp_pre_30       13752 non-null  float64
 14  Temp_pre_15       13752 non-null  float64
 15  Temp_pre_7        13752 non-null  float64
 16  Temp_cont         13752 non-null  float64
 17  Wind_pre_30       13752 non-null  float64
 18  Wind_pre_15       13752 non-null  float64
 19  Wind_pre_7        13752 non-null  float64
 20  Wind_cont         13752 non-null  float64
 21  Hum_pre_30        13752 non-null  float64
 22  Hum_pre_15        13752 non-null  float64
 23  Hum_pre_7         13752 non-null  float64
 24  Hum_cont          13752 non-null  float64
 25  Prec_pre_30       13752 non-null  float64
 26  Prec_pre_15       13752 non-null  float64
 27  Prec_pre_7        13752 non-null  float64
 28  Prec_cont         13752 non-null  float64
 29  remoteness        13752 non-null  float64
 30  year              13752 non-null  int64
dtypes: datetime64[ns](1), float64(21), int64(2), object(7)
memory usage: 3.4+ MB

In [9]:
df['disc_clean_date'] = pd.to_datetime(df['disc_clean_date'].str.strip(), format='%m/%d/%Y')
df['year'] = df.disc_clean_date.dt.year

C:\Users\KATLIN\AppData\Local\Temp/ipykernel_24876/4126329642.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['disc_clean_date'] = pd.to_datetime(df['disc_clean_date'].str.strip(), format='%m/%d/%Y')
C:\Users\KATLIN\AppData\Local\Temp/ipykernel_24876/4126329642.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['year'] = df.disc_clean_date.dt.year

In [10]:
df_new.to_csv("cleaned_wildfire_1.csv")

In [11]:
df_new

,fire_name,fire_size,fire_size_class,stat_cause_descr,latitude,longitude,state,disc_clean_date,cont_clean_date,discovery_month,...,Hum_pre_30,Hum_pre_15,Hum_pre_7,Hum_cont,Prec_pre_30,Prec_pre_15,Prec_pre_7,Prec_cont,remoteness,year
3,WNA 1,1.00,B,Debris Burning,39.641400,-119.308300,NV,2005-06-06,6/6/2005,Jun,...,44.778429,37.140811,35.353846,0.000000,10.4,7.2,0.0,0.0,0.487447,2005
9,CRAZY,1.00,B,Miscellaneous,48.839400,-99.718500,ND,2004-04-19,4/19/2004,Apr,...,64.606509,55.943038,54.337838,0.000000,12.3,1.8,0.0,0.0,0.291683,2004
26,STO3573155,2.00,B,Debris Burning,35.718900,-92.335000,AR,2014-01-19,1/19/2014,Jan,...,76.091398,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.227270,2014
31,AXE RONDEAU,1.20,B,Debris Burning,48.833000,-99.783600,ND,2007-04-07,4/7/2007,Apr,...,77.575012,75.963981,71.173116,0.000000,21.2,21.2,9.2,0.0,0.292303,2007
35,FY2001-EARLY-021,30.18,C,Debris Burning,31.259000,-84.895600,GA,2000-10-19,10/19/2000,Oct,...,67.551783,61.733788,60.328571,0.000000,0.0,0.0,0.0,0.0,0.162416,2000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55342,PINECREST,5086.00,G,Debris Burning,45.656100,-109.114200,MT,2015-03-28,4/2/2015,Mar,...,51.676681,46.933399,42.638384,28.844444,0.0,0.0,0.0,0.0,0.046649,2015
55343,WALKER,5963.00,G,Debris Burning,43.785671,-115.985922,ID,2015-10-10,10/20/2015,Oct,...,51.541802,53.945191,56.257500,49.915194,0.0,0.0,0.0,0.0,0.060013,2015
55349,BROWN RANCH,17831.00,G,Miscellaneous,30.005000,-100.391167,TX,2015-08-10,8/16/2015,Aug,...,60.470917,56.987013,58.615538,58.243619,0.0,0.0,0.0,0.0,0.451149,2015
55350,PRICKLEY PEAR,3452.00,F,Miscellaneous,30.400883,-101.331933,TX,2015-08-28,8/30/2015,Aug,...,44.411268,47.176638,47.944785,39.510638,4.6,4.6,0.0,0.0,0.429604,2015
55351,COTTONWOOD GULCH,8300.00,G,Miscellaneous,45.922100,-111.422500,MT,2015-10-11,10/16/2015,Oct,...,60.914780,62.120643,66.795455,48.628099,15.8,2.8,2.8,0.0,0.009711,2015

In [12]:
df_new.drop(["disc_clean_date", "cont_clean_date", "fire_mag", "fire_size_class"], axis=1, inplace=True)

C:\Users\KATLIN\anaconda3\envs\PythonData\lib\site-packages\pandas\core\frame.py:4906: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

In [13]:
df_new

,fire_name,fire_size,stat_cause_descr,latitude,longitude,state,discovery_month,putout_time,Vegetation,Temp_pre_30,...,Hum_pre_30,Hum_pre_15,Hum_pre_7,Hum_cont,Prec_pre_30,Prec_pre_15,Prec_pre_7,Prec_cont,remoteness,year
3,WNA 1,1.00,Debris Burning,39.641400,-119.308300,NV,Jun,0 days 00:00:00.000000000,0,16.275967,...,44.778429,37.140811,35.353846,0.000000,10.4,7.2,0.0,0.0,0.487447,2005
9,CRAZY,1.00,Miscellaneous,48.839400,-99.718500,ND,Apr,0 days 00:00:00.000000000,15,4.600950,...,64.606509,55.943038,54.337838,0.000000,12.3,1.8,0.0,0.0,0.291683,2004
26,STO3573155,2.00,Debris Burning,35.718900,-92.335000,AR,Jan,0 days 00:00:00.000000000,15,3.490698,...,76.091398,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.227270,2014
31,AXE RONDEAU,1.20,Debris Burning,48.833000,-99.783600,ND,Apr,0 days 00:00:00.000000000,15,-0.891635,...,77.575012,75.963981,71.173116,0.000000,21.2,21.2,9.2,0.0,0.292303,2007
35,FY2001-EARLY-021,30.18,Debris Burning,31.259000,-84.895600,GA,Oct,0 days 00:00:00.000000000,12,20.079480,...,67.551783,61.733788,60.328571,0.000000,0.0,0.0,0.0,0.0,0.162416,2000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55342,PINECREST,5086.00,Debris Burning,45.656100,-109.114200,MT,Mar,5,15,2.275974,...,51.676681,46.933399,42.638384,28.844444,0.0,0.0,0.0,0.0,0.046649,2015
55343,WALKER,5963.00,Debris Burning,43.785671,-115.985922,ID,Oct,10,9,17.007551,...,51.541802,53.945191,56.257500,49.915194,0.0,0.0,0.0,0.0,0.060013,2015
55349,BROWN RANCH,17831.00,Miscellaneous,30.005000,-100.391167,TX,Aug,6,12,28.113120,...,60.470917,56.987013,58.615538,58.243619,0.0,0.0,0.0,0.0,0.451149,2015
55350,PRICKLEY PEAR,3452.00,Miscellaneous,30.400883,-101.331933,TX,Aug,2,12,31.270833,...,44.411268,47.176638,47.944785,39.510638,4.6,4.6,0.0,0.0,0.429604,2015
55351,COTTONWOOD GULCH,8300.00,Miscellaneous,45.922100,-111.422500,MT,Oct,5,15,12.855921,...,60.914780,62.120643,66.795455,48.628099,15.8,2.8,2.8,0.0,0.009711,2015

In [14]:
df_new["putout_time"].value_counts

<bound method IndexOpsMixin.value_counts of 3        0 days 00:00:00.000000000
9        0 days 00:00:00.000000000
26       0 days 00:00:00.000000000
31       0 days 00:00:00.000000000
35       0 days 00:00:00.000000000
                   ...
55342                            5
55343                           10
55349                            6
55350                            2
55351                            5
Name: putout_time, Length: 13752, dtype: object>

In [15]:
df_new["putout_time"]=df_new["putout_time"].map(lambda x : 0 if x[:6]=="0 days" else x)
df_new

C:\Users\KATLIN\AppData\Local\Temp/ipykernel_24876/3139877183.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new["putout_time"]=df_new["putout_time"].map(lambda x : 0 if x[:6]=="0 days" else x)

,fire_name,fire_size,stat_cause_descr,latitude,longitude,state,discovery_month,putout_time,Vegetation,Temp_pre_30,...,Hum_pre_30,Hum_pre_15,Hum_pre_7,Hum_cont,Prec_pre_30,Prec_pre_15,Prec_pre_7,Prec_cont,remoteness,year
3,WNA 1,1.00,Debris Burning,39.641400,-119.308300,NV,Jun,0,0,16.275967,...,44.778429,37.140811,35.353846,0.000000,10.4,7.2,0.0,0.0,0.487447,2005
9,CRAZY,1.00,Miscellaneous,48.839400,-99.718500,ND,Apr,0,15,4.600950,...,64.606509,55.943038,54.337838,0.000000,12.3,1.8,0.0,0.0,0.291683,2004
26,STO3573155,2.00,Debris Burning,35.718900,-92.335000,AR,Jan,0,15,3.490698,...,76.091398,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.227270,2014
31,AXE RONDEAU,1.20,Debris Burning,48.833000,-99.783600,ND,Apr,0,15,-0.891635,...,77.575012,75.963981,71.173116,0.000000,21.2,21.2,9.2,0.0,0.292303,2007
35,FY2001-EARLY-021,30.18,Debris Burning,31.259000,-84.895600,GA,Oct,0,12,20.079480,...,67.551783,61.733788,60.328571,0.000000,0.0,0.0,0.0,0.0,0.162416,2000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55342,PINECREST,5086.00,Debris Burning,45.656100,-109.114200,MT,Mar,5,15,2.275974,...,51.676681,46.933399,42.638384,28.844444,0.0,0.0,0.0,0.0,0.046649,2015
55343,WALKER,5963.00,Debris Burning,43.785671,-115.985922,ID,Oct,10,9,17.007551,...,51.541802,53.945191,56.257500,49.915194,0.0,0.0,0.0,0.0,0.060013,2015
55349,BROWN RANCH,17831.00,Miscellaneous,30.005000,-100.391167,TX,Aug,6,12,28.113120,...,60.470917,56.987013,58.615538,58.243619,0.0,0.0,0.0,0.0,0.451149,2015
55350,PRICKLEY PEAR,3452.00,Miscellaneous,30.400883,-101.331933,TX,Aug,2,12,31.270833,...,44.411268,47.176638,47.944785,39.510638,4.6,4.6,0.0,0.0,0.429604,2015
55351,COTTONWOOD GULCH,8300.00,Miscellaneous,45.922100,-111.422500,MT,Oct,5,15,12.855921,...,60.914780,62.120643,66.795455,48.628099,15.8,2.8,2.8,0.0,0.009711,2015

In [16]:
df_new

,fire_name,fire_size,stat_cause_descr,latitude,longitude,state,discovery_month,putout_time,Vegetation,Temp_pre_30,...,Hum_pre_30,Hum_pre_15,Hum_pre_7,Hum_cont,Prec_pre_30,Prec_pre_15,Prec_pre_7,Prec_cont,remoteness,year
3,WNA 1,1.00,Debris Burning,39.641400,-119.308300,NV,Jun,0,0,16.275967,...,44.778429,37.140811,35.353846,0.000000,10.4,7.2,0.0,0.0,0.487447,2005
9,CRAZY,1.00,Miscellaneous,48.839400,-99.718500,ND,Apr,0,15,4.600950,...,64.606509,55.943038,54.337838,0.000000,12.3,1.8,0.0,0.0,0.291683,2004
26,STO3573155,2.00,Debris Burning,35.718900,-92.335000,AR,Jan,0,15,3.490698,...,76.091398,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.227270,2014
31,AXE RONDEAU,1.20,Debris Burning,48.833000,-99.783600,ND,Apr,0,15,-0.891635,...,77.575012,75.963981,71.173116,0.000000,21.2,21.2,9.2,0.0,0.292303,2007
35,FY2001-EARLY-021,30.18,Debris Burning,31.259000,-84.895600,GA,Oct,0,12,20.079480,...,67.551783,61.733788,60.328571,0.000000,0.0,0.0,0.0,0.0,0.162416,2000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55342,PINECREST,5086.00,Debris Burning,45.656100,-109.114200,MT,Mar,5,15,2.275974,...,51.676681,46.933399,42.638384,28.844444,0.0,0.0,0.0,0.0,0.046649,2015
55343,WALKER,5963.00,Debris Burning,43.785671,-115.985922,ID,Oct,10,9,17.007551,...,51.541802,53.945191,56.257500,49.915194,0.0,0.0,0.0,0.0,0.060013,2015
55349,BROWN RANCH,17831.00,Miscellaneous,30.005000,-100.391167,TX,Aug,6,12,28.113120,...,60.470917,56.987013,58.615538,58.243619,0.0,0.0,0.0,0.0,0.451149,2015
55350,PRICKLEY PEAR,3452.00,Miscellaneous,30.400883,-101.331933,TX,Aug,2,12,31.270833,...,44.411268,47.176638,47.944785,39.510638,4.6,4.6,0.0,0.0,0.429604,2015
55351,COTTONWOOD GULCH,8300.00,Miscellaneous,45.922100,-111.422500,MT,Oct,5,15,12.855921,...,60.914780,62.120643,66.795455,48.628099,15.8,2.8,2.8,0.0,0.009711,2015

In [18]:
df.to_csv("Resources/cleaned_wildfire_2.csv")