In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("Resources/Original Data/FW_Veg_Rem_Combined_ORIGINAL.csv",index_col=False)
df

,Unnamed: 0,Unnamed: 0.1,fire_name,fire_size,fire_size_class,stat_cause_descr,latitude,longitude,state,disc_clean_date,...,Wind_cont,Hum_pre_30,Hum_pre_15,Hum_pre_7,Hum_cont,Prec_pre_30,Prec_pre_15,Prec_pre_7,Prec_cont,remoteness
0,0,0,NaN,10.0,C,Missing/Undefined,18.105072,-66.753044,PR,2/11/2007,...,3.250413,78.216590,76.793750,76.381579,78.724370,0.0,0.0,0.0,0.0,0.017923
1,1,1,NaN,3.0,B,Arson,35.038330,-87.610000,TN,12/11/2006,...,2.122320,70.840000,65.858911,55.505882,81.682678,59.8,8.4,0.0,86.8,0.184355
2,2,2,NaN,60.0,C,Arson,34.947800,-88.722500,MS,2/29/2004,...,3.369050,75.531629,75.868613,76.812834,65.063800,168.8,42.2,18.1,124.5,0.194544
3,3,3,WNA 1,1.0,B,Debris Burning,39.641400,-119.308300,NV,6/6/2005,...,0.000000,44.778429,37.140811,35.353846,0.000000,10.4,7.2,0.0,0.0,0.487447
4,4,4,NaN,2.0,B,Miscellaneous,30.700600,-90.591400,LA,9/22/1999,...,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.0,-1.0,-1.0,-1.0,0.214633
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55362,55362,55362,IMPACT,6289.0,G,Missing/Undefined,39.180000,-96.784167,KS,10/15/2015,...,3.804803,65.671410,61.839572,54.625698,55.042092,35.4,8.2,0.0,249.0,0.331501
55363,55363,55363,BUTTE,70868.0,G,Missing/Undefined,38.342719,-120.695967,CA,9/9/2015,...,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.0,-1.0,-1.0,-1.0,0.124683
55364,55364,55364,WILLOW,5702.0,G,Arson,37.262607,-119.511139,CA,7/25/2015,...,2.529158,43.755556,43.755556,44.443975,35.924406,0.0,0.0,0.0,0.0,0.097682
55365,55365,55365,BARKER,3261.0,F,Miscellaneous,40.604300,-123.080450,CA,7/31/2015,...,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.0,-1.0,-1.0,-1.0,0.178206
55366,55366,55366,VALLEY,76067.0,G,Missing/Undefined,38.843988,-122.759707,CA,9/12/2015,...,1.208073,50.521912,46.310627,37.178571,58.063802,0.3,0.3,0.0,18.8,0.167305

In [3]:
df.columns

Index(['Unnamed: 0', 'Unnamed: 0.1', 'fire_name', 'fire_size',
       'fire_size_class', 'stat_cause_descr', 'latitude', 'longitude', 'state',
       'disc_clean_date', 'cont_clean_date', 'discovery_month',
       'disc_date_final', 'cont_date_final', 'putout_time', 'disc_date_pre',
       'disc_pre_year', 'disc_pre_month', 'wstation_usaf', 'dstation_m',
       'wstation_wban', 'wstation_byear', 'wstation_eyear', 'Vegetation',
       'fire_mag', 'weather_file', 'Temp_pre_30', 'Temp_pre_15', 'Temp_pre_7',
       'Temp_cont', 'Wind_pre_30', 'Wind_pre_15', 'Wind_pre_7', 'Wind_cont',
       'Hum_pre_30', 'Hum_pre_15', 'Hum_pre_7', 'Hum_cont', 'Prec_pre_30',
       'Prec_pre_15', 'Prec_pre_7', 'Prec_cont', 'remoteness'],
      dtype='object')

In [4]:
df=df.drop(columns="fire_name")

In [5]:
df=df.dropna()
df

,Unnamed: 0,Unnamed: 0.1,fire_size,fire_size_class,stat_cause_descr,latitude,longitude,state,disc_clean_date,cont_clean_date,...,Wind_cont,Hum_pre_30,Hum_pre_15,Hum_pre_7,Hum_cont,Prec_pre_30,Prec_pre_15,Prec_pre_7,Prec_cont,remoteness
3,3,3,1.0,B,Debris Burning,39.641400,-119.308300,NV,6/6/2005,6/6/2005,...,0.000000,44.778429,37.140811,35.353846,0.000000,10.4,7.2,0.0,0.0,0.487447
9,9,9,1.0,B,Miscellaneous,48.839400,-99.718500,ND,4/19/2004,4/19/2004,...,0.000000,64.606509,55.943038,54.337838,0.000000,12.3,1.8,0.0,0.0,0.291683
22,22,22,2.0,B,Miscellaneous,40.843386,-73.316419,NY,4/18/2004,4/18/2004,...,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.0,-1.0,-1.0,-1.0,0.054988
24,24,24,40.0,C,Arson,31.435181,-88.999489,MS,4/3/1999,4/3/1999,...,0.000000,57.997207,56.747191,59.614458,0.000000,0.0,0.0,0.0,0.0,0.199485
26,26,26,2.0,B,Debris Burning,35.718900,-92.335000,AR,1/19/2014,1/19/2014,...,0.000000,76.091398,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.227270
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55349,55349,55349,17831.0,G,Miscellaneous,30.005000,-100.391167,TX,8/10/2015,8/16/2015,...,2.360093,60.470917,56.987013,58.615538,58.243619,0.0,0.0,0.0,0.0,0.451149
55350,55350,55350,3452.0,F,Miscellaneous,30.400883,-101.331933,TX,8/28/2015,8/30/2015,...,3.082979,44.411268,47.176638,47.944785,39.510638,4.6,4.6,0.0,0.0,0.429604
55351,55351,55351,8300.0,G,Miscellaneous,45.922100,-111.422500,MT,10/11/2015,10/16/2015,...,3.367769,60.914780,62.120643,66.795455,48.628099,15.8,2.8,2.8,0.0,0.009711
55363,55363,55363,70868.0,G,Missing/Undefined,38.342719,-120.695967,CA,9/9/2015,10/1/2015,...,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.0,-1.0,-1.0,-1.0,0.124683
55365,55365,55365,3261.0,F,Miscellaneous,40.604300,-123.080450,CA,7/31/2015,9/12/2015,...,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.0,-1.0,-1.0,-1.0,0.178206

In [6]:
df_new=df[['fire_size',
       'fire_size_class', 'stat_cause_descr', 'latitude', 'longitude', 'state',
       'disc_clean_date', 'cont_clean_date', 'discovery_month',
       'putout_time',  'Vegetation','fire_mag', 'Temp_pre_30', 'Temp_pre_15', 'Temp_pre_7',
       'Temp_cont', 'Wind_pre_30', 'Wind_pre_15', 'Wind_pre_7', 'Wind_cont',
       'Hum_pre_30', 'Hum_pre_15', 'Hum_pre_7', 'Hum_cont', 'Prec_pre_30',
       'Prec_pre_15', 'Prec_pre_7', 'Prec_cont', 'remoteness']]
df_new

,fire_size,fire_size_class,stat_cause_descr,latitude,longitude,state,disc_clean_date,cont_clean_date,discovery_month,putout_time,...,Wind_cont,Hum_pre_30,Hum_pre_15,Hum_pre_7,Hum_cont,Prec_pre_30,Prec_pre_15,Prec_pre_7,Prec_cont,remoteness
3,1.0,B,Debris Burning,39.641400,-119.308300,NV,6/6/2005,6/6/2005,Jun,0 days 00:00:00.000000000,...,0.000000,44.778429,37.140811,35.353846,0.000000,10.4,7.2,0.0,0.0,0.487447
9,1.0,B,Miscellaneous,48.839400,-99.718500,ND,4/19/2004,4/19/2004,Apr,0 days 00:00:00.000000000,...,0.000000,64.606509,55.943038,54.337838,0.000000,12.3,1.8,0.0,0.0,0.291683
22,2.0,B,Miscellaneous,40.843386,-73.316419,NY,4/18/2004,4/18/2004,Apr,0 days 00:00:00.000000000,...,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.0,-1.0,-1.0,-1.0,0.054988
24,40.0,C,Arson,31.435181,-88.999489,MS,4/3/1999,4/3/1999,Apr,0 days 00:00:00.000000000,...,0.000000,57.997207,56.747191,59.614458,0.000000,0.0,0.0,0.0,0.0,0.199485
26,2.0,B,Debris Burning,35.718900,-92.335000,AR,1/19/2014,1/19/2014,Jan,0 days 00:00:00.000000000,...,0.000000,76.091398,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.227270
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55349,17831.0,G,Miscellaneous,30.005000,-100.391167,TX,8/10/2015,8/16/2015,Aug,6,...,2.360093,60.470917,56.987013,58.615538,58.243619,0.0,0.0,0.0,0.0,0.451149
55350,3452.0,F,Miscellaneous,30.400883,-101.331933,TX,8/28/2015,8/30/2015,Aug,2,...,3.082979,44.411268,47.176638,47.944785,39.510638,4.6,4.6,0.0,0.0,0.429604
55351,8300.0,G,Miscellaneous,45.922100,-111.422500,MT,10/11/2015,10/16/2015,Oct,5,...,3.367769,60.914780,62.120643,66.795455,48.628099,15.8,2.8,2.8,0.0,0.009711
55363,70868.0,G,Missing/Undefined,38.342719,-120.695967,CA,9/9/2015,10/1/2015,Sep,22,...,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.0,-1.0,-1.0,-1.0,0.124683
55365,3261.0,F,Miscellaneous,40.604300,-123.080450,CA,7/31/2015,9/12/2015,Jul,43,...,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.0,-1.0,-1.0,-1.0,0.178206

In [7]:
df_new['disc_clean_date'] = pd.to_datetime(df_new['disc_clean_date'].str.strip(), format='%m/%d/%Y')
df_new['year'] = df_new.disc_clean_date.dt.year

C:\Users\KATLIN\AppData\Local\Temp/ipykernel_17864/216051678.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new['disc_clean_date'] = pd.to_datetime(df_new['disc_clean_date'].str.strip(), format='%m/%d/%Y')
C:\Users\KATLIN\AppData\Local\Temp/ipykernel_17864/216051678.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new['year'] = df_new.disc_clean_date.dt.year

In [8]:
df_new= df_new[df_new.Temp_pre_30 != -1.0]
df_new

,fire_size,fire_size_class,stat_cause_descr,latitude,longitude,state,disc_clean_date,cont_clean_date,discovery_month,putout_time,...,Hum_pre_30,Hum_pre_15,Hum_pre_7,Hum_cont,Prec_pre_30,Prec_pre_15,Prec_pre_7,Prec_cont,remoteness,year
3,1.0,B,Debris Burning,39.641400,-119.308300,NV,2005-06-06,6/6/2005,Jun,0 days 00:00:00.000000000,...,44.778429,37.140811,35.353846,0.000000,10.4,7.2,0.0,0.0,0.487447,2005
9,1.0,B,Miscellaneous,48.839400,-99.718500,ND,2004-04-19,4/19/2004,Apr,0 days 00:00:00.000000000,...,64.606509,55.943038,54.337838,0.000000,12.3,1.8,0.0,0.0,0.291683,2004
24,40.0,C,Arson,31.435181,-88.999489,MS,1999-04-03,4/3/1999,Apr,0 days 00:00:00.000000000,...,57.997207,56.747191,59.614458,0.000000,0.0,0.0,0.0,0.0,0.199485,1999
26,2.0,B,Debris Burning,35.718900,-92.335000,AR,2014-01-19,1/19/2014,Jan,0 days 00:00:00.000000000,...,76.091398,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.227270,2014
31,1.2,B,Debris Burning,48.833000,-99.783600,ND,2007-04-07,4/7/2007,Apr,0 days 00:00:00.000000000,...,77.575012,75.963981,71.173116,0.000000,21.2,21.2,9.2,0.0,0.292303,2007
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55342,5086.0,G,Debris Burning,45.656100,-109.114200,MT,2015-03-28,4/2/2015,Mar,5,...,51.676681,46.933399,42.638384,28.844444,0.0,0.0,0.0,0.0,0.046649,2015
55343,5963.0,G,Debris Burning,43.785671,-115.985922,ID,2015-10-10,10/20/2015,Oct,10,...,51.541802,53.945191,56.257500,49.915194,0.0,0.0,0.0,0.0,0.060013,2015
55349,17831.0,G,Miscellaneous,30.005000,-100.391167,TX,2015-08-10,8/16/2015,Aug,6,...,60.470917,56.987013,58.615538,58.243619,0.0,0.0,0.0,0.0,0.451149,2015
55350,3452.0,F,Miscellaneous,30.400883,-101.331933,TX,2015-08-28,8/30/2015,Aug,2,...,44.411268,47.176638,47.944785,39.510638,4.6,4.6,0.0,0.0,0.429604,2015
55351,8300.0,G,Miscellaneous,45.922100,-111.422500,MT,2015-10-11,10/16/2015,Oct,5,...,60.914780,62.120643,66.795455,48.628099,15.8,2.8,2.8,0.0,0.009711,2015

In [9]:
df_new.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 18918 entries, 3 to 55351
Data columns (total 30 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   fire_size         18918 non-null  float64
 1   fire_size_class   18918 non-null  object
 2   stat_cause_descr  18918 non-null  object
 3   latitude          18918 non-null  float64
 4   longitude         18918 non-null  float64
 5   state             18918 non-null  object
 6   disc_clean_date   18918 non-null  datetime64[ns]
 7   cont_clean_date   18918 non-null  object
 8   discovery_month   18918 non-null  object
 9   putout_time       18918 non-null  object
 10  Vegetation        18918 non-null  int64
 11  fire_mag          18918 non-null  float64
 12  Temp_pre_30       18918 non-null  float64
 13  Temp_pre_15       18918 non-null  float64
 14  Temp_pre_7        18918 non-null  float64
 15  Temp_cont         18918 non-null  float64
 16  Wind_pre_30       18918 non-null  float64
 17  Wind_pre_15       18918 non-null  float64
 18  Wind_pre_7        18918 non-null  float64
 19  Wind_cont         18918 non-null  float64
 20  Hum_pre_30        18918 non-null  float64
 21  Hum_pre_15        18918 non-null  float64
 22  Hum_pre_7         18918 non-null  float64
 23  Hum_cont          18918 non-null  float64
 24  Prec_pre_30       18918 non-null  float64
 25  Prec_pre_15       18918 non-null  float64
 26  Prec_pre_7        18918 non-null  float64
 27  Prec_cont         18918 non-null  float64
 28  remoteness        18918 non-null  float64
 29  year              18918 non-null  int64
dtypes: datetime64[ns](1), float64(21), int64(2), object(6)
memory usage: 4.5+ MB

In [10]:
df['disc_clean_date'] = pd.to_datetime(df['disc_clean_date'].str.strip(), format='%m/%d/%Y')
df['year'] = df.disc_clean_date.dt.year

In [11]:
#df_new.to_csv("cleaned_wildfire_1.csv")

In [12]:
df_new

,fire_size,fire_size_class,stat_cause_descr,latitude,longitude,state,disc_clean_date,cont_clean_date,discovery_month,putout_time,...,Hum_pre_30,Hum_pre_15,Hum_pre_7,Hum_cont,Prec_pre_30,Prec_pre_15,Prec_pre_7,Prec_cont,remoteness,year
3,1.0,B,Debris Burning,39.641400,-119.308300,NV,2005-06-06,6/6/2005,Jun,0 days 00:00:00.000000000,...,44.778429,37.140811,35.353846,0.000000,10.4,7.2,0.0,0.0,0.487447,2005
9,1.0,B,Miscellaneous,48.839400,-99.718500,ND,2004-04-19,4/19/2004,Apr,0 days 00:00:00.000000000,...,64.606509,55.943038,54.337838,0.000000,12.3,1.8,0.0,0.0,0.291683,2004
24,40.0,C,Arson,31.435181,-88.999489,MS,1999-04-03,4/3/1999,Apr,0 days 00:00:00.000000000,...,57.997207,56.747191,59.614458,0.000000,0.0,0.0,0.0,0.0,0.199485,1999
26,2.0,B,Debris Burning,35.718900,-92.335000,AR,2014-01-19,1/19/2014,Jan,0 days 00:00:00.000000000,...,76.091398,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.227270,2014
31,1.2,B,Debris Burning,48.833000,-99.783600,ND,2007-04-07,4/7/2007,Apr,0 days 00:00:00.000000000,...,77.575012,75.963981,71.173116,0.000000,21.2,21.2,9.2,0.0,0.292303,2007
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55342,5086.0,G,Debris Burning,45.656100,-109.114200,MT,2015-03-28,4/2/2015,Mar,5,...,51.676681,46.933399,42.638384,28.844444,0.0,0.0,0.0,0.0,0.046649,2015
55343,5963.0,G,Debris Burning,43.785671,-115.985922,ID,2015-10-10,10/20/2015,Oct,10,...,51.541802,53.945191,56.257500,49.915194,0.0,0.0,0.0,0.0,0.060013,2015
55349,17831.0,G,Miscellaneous,30.005000,-100.391167,TX,2015-08-10,8/16/2015,Aug,6,...,60.470917,56.987013,58.615538,58.243619,0.0,0.0,0.0,0.0,0.451149,2015
55350,3452.0,F,Miscellaneous,30.400883,-101.331933,TX,2015-08-28,8/30/2015,Aug,2,...,44.411268,47.176638,47.944785,39.510638,4.6,4.6,0.0,0.0,0.429604,2015
55351,8300.0,G,Miscellaneous,45.922100,-111.422500,MT,2015-10-11,10/16/2015,Oct,5,...,60.914780,62.120643,66.795455,48.628099,15.8,2.8,2.8,0.0,0.009711,2015

In [13]:
df_new.drop(["disc_clean_date", "cont_clean_date", "fire_mag", "fire_size_class"], axis=1, inplace=True)

C:\Users\KATLIN\anaconda3\envs\PythonData\lib\site-packages\pandas\core\frame.py:4906: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

In [14]:
df_new

,fire_size,stat_cause_descr,latitude,longitude,state,discovery_month,putout_time,Vegetation,Temp_pre_30,Temp_pre_15,...,Hum_pre_30,Hum_pre_15,Hum_pre_7,Hum_cont,Prec_pre_30,Prec_pre_15,Prec_pre_7,Prec_cont,remoteness,year
3,1.0,Debris Burning,39.641400,-119.308300,NV,Jun,0 days 00:00:00.000000000,0,16.275967,18.996181,...,44.778429,37.140811,35.353846,0.000000,10.4,7.2,0.0,0.0,0.487447,2005
9,1.0,Miscellaneous,48.839400,-99.718500,ND,Apr,0 days 00:00:00.000000000,15,4.600950,6.861878,...,64.606509,55.943038,54.337838,0.000000,12.3,1.8,0.0,0.0,0.291683,2004
24,40.0,Arson,31.435181,-88.999489,MS,Apr,0 days 00:00:00.000000000,12,13.468619,15.067227,...,57.997207,56.747191,59.614458,0.000000,0.0,0.0,0.0,0.0,0.199485,1999
26,2.0,Debris Burning,35.718900,-92.335000,AR,Jan,0 days 00:00:00.000000000,15,3.490698,0.000000,...,76.091398,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.227270,2014
31,1.2,Debris Burning,48.833000,-99.783600,ND,Apr,0 days 00:00:00.000000000,15,-0.891635,0.372659,...,77.575012,75.963981,71.173116,0.000000,21.2,21.2,9.2,0.0,0.292303,2007
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55342,5086.0,Debris Burning,45.656100,-109.114200,MT,Mar,5,15,2.275974,7.360185,...,51.676681,46.933399,42.638384,28.844444,0.0,0.0,0.0,0.0,0.046649,2015
55343,5963.0,Debris Burning,43.785671,-115.985922,ID,Oct,10,9,17.007551,16.983670,...,51.541802,53.945191,56.257500,49.915194,0.0,0.0,0.0,0.0,0.060013,2015
55349,17831.0,Miscellaneous,30.005000,-100.391167,TX,Aug,6,12,28.113120,28.826531,...,60.470917,56.987013,58.615538,58.243619,0.0,0.0,0.0,0.0,0.451149,2015
55350,3452.0,Miscellaneous,30.400883,-101.331933,TX,Aug,2,12,31.270833,30.603352,...,44.411268,47.176638,47.944785,39.510638,4.6,4.6,0.0,0.0,0.429604,2015
55351,8300.0,Miscellaneous,45.922100,-111.422500,MT,Oct,5,15,12.855921,11.724403,...,60.914780,62.120643,66.795455,48.628099,15.8,2.8,2.8,0.0,0.009711,2015

In [15]:
df_new["putout_time"].value_counts

<bound method IndexOpsMixin.value_counts of 3        0 days 00:00:00.000000000
9        0 days 00:00:00.000000000
24       0 days 00:00:00.000000000
26       0 days 00:00:00.000000000
31       0 days 00:00:00.000000000
                   ...
55342                            5
55343                           10
55349                            6
55350                            2
55351                            5
Name: putout_time, Length: 18918, dtype: object>

In [16]:
df_new["putout_time"]=df_new["putout_time"].map(lambda x : 0 if x[:6]=="0 days" else x)
df_new

C:\Users\KATLIN\AppData\Local\Temp/ipykernel_17864/3139877183.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new["putout_time"]=df_new["putout_time"].map(lambda x : 0 if x[:6]=="0 days" else x)

,fire_size,stat_cause_descr,latitude,longitude,state,discovery_month,putout_time,Vegetation,Temp_pre_30,Temp_pre_15,...,Hum_pre_30,Hum_pre_15,Hum_pre_7,Hum_cont,Prec_pre_30,Prec_pre_15,Prec_pre_7,Prec_cont,remoteness,year
3,1.0,Debris Burning,39.641400,-119.308300,NV,Jun,0,0,16.275967,18.996181,...,44.778429,37.140811,35.353846,0.000000,10.4,7.2,0.0,0.0,0.487447,2005
9,1.0,Miscellaneous,48.839400,-99.718500,ND,Apr,0,15,4.600950,6.861878,...,64.606509,55.943038,54.337838,0.000000,12.3,1.8,0.0,0.0,0.291683,2004
24,40.0,Arson,31.435181,-88.999489,MS,Apr,0,12,13.468619,15.067227,...,57.997207,56.747191,59.614458,0.000000,0.0,0.0,0.0,0.0,0.199485,1999
26,2.0,Debris Burning,35.718900,-92.335000,AR,Jan,0,15,3.490698,0.000000,...,76.091398,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.227270,2014
31,1.2,Debris Burning,48.833000,-99.783600,ND,Apr,0,15,-0.891635,0.372659,...,77.575012,75.963981,71.173116,0.000000,21.2,21.2,9.2,0.0,0.292303,2007
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55342,5086.0,Debris Burning,45.656100,-109.114200,MT,Mar,5,15,2.275974,7.360185,...,51.676681,46.933399,42.638384,28.844444,0.0,0.0,0.0,0.0,0.046649,2015
55343,5963.0,Debris Burning,43.785671,-115.985922,ID,Oct,10,9,17.007551,16.983670,...,51.541802,53.945191,56.257500,49.915194,0.0,0.0,0.0,0.0,0.060013,2015
55349,17831.0,Miscellaneous,30.005000,-100.391167,TX,Aug,6,12,28.113120,28.826531,...,60.470917,56.987013,58.615538,58.243619,0.0,0.0,0.0,0.0,0.451149,2015
55350,3452.0,Miscellaneous,30.400883,-101.331933,TX,Aug,2,12,31.270833,30.603352,...,44.411268,47.176638,47.944785,39.510638,4.6,4.6,0.0,0.0,0.429604,2015
55351,8300.0,Miscellaneous,45.922100,-111.422500,MT,Oct,5,15,12.855921,11.724403,...,60.914780,62.120643,66.795455,48.628099,15.8,2.8,2.8,0.0,0.009711,2015

In [17]:
df_new.loc[df_new["putout_time"]==0]

,fire_size,stat_cause_descr,latitude,longitude,state,discovery_month,putout_time,Vegetation,Temp_pre_30,Temp_pre_15,...,Hum_pre_30,Hum_pre_15,Hum_pre_7,Hum_cont,Prec_pre_30,Prec_pre_15,Prec_pre_7,Prec_cont,remoteness,year
3,1.0,Debris Burning,39.641400,-119.308300,NV,Jun,0,0,16.275967,18.996181,...,44.778429,37.140811,35.353846,0.0,10.4,7.2,0.0,0.0,0.487447,2005
9,1.0,Miscellaneous,48.839400,-99.718500,ND,Apr,0,15,4.600950,6.861878,...,64.606509,55.943038,54.337838,0.0,12.3,1.8,0.0,0.0,0.291683,2004
24,40.0,Arson,31.435181,-88.999489,MS,Apr,0,12,13.468619,15.067227,...,57.997207,56.747191,59.614458,0.0,0.0,0.0,0.0,0.0,0.199485,1999
26,2.0,Debris Burning,35.718900,-92.335000,AR,Jan,0,15,3.490698,0.000000,...,76.091398,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.227270,2014
31,1.2,Debris Burning,48.833000,-99.783600,ND,Apr,0,15,-0.891635,0.372659,...,77.575012,75.963981,71.173116,0.0,21.2,21.2,9.2,0.0,0.292303,2007
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49987,73.0,Arson,33.991263,-85.676255,AL,Aug,0,16,23.081575,23.946629,...,74.967606,75.695775,73.377246,0.0,0.0,0.0,0.0,0.0,0.167517,2006
49988,1.1,Debris Burning,33.717731,-83.228058,GA,Dec,0,16,8.169864,8.044944,...,73.003354,68.946667,74.368534,0.0,0.0,0.0,0.0,0.0,0.145718,2013
49989,3.5,Miscellaneous,42.412639,-73.674227,NY,Mar,0,9,-1.564737,0.773558,...,67.689175,61.765854,54.763441,0.0,57.8,19.5,2.5,0.0,0.057448,2009
49994,1.0,Miscellaneous,37.976100,-90.759000,MO,Apr,0,0,9.162112,11.540315,...,61.657784,63.733396,58.176353,0.0,91.6,69.4,16.0,0.0,0.211468,2014
49995,1.0,Children,47.270800,-95.621400,MN,Mar,0,15,-9.592386,-0.404299,...,74.901503,78.071125,76.389262,0.0,0.0,0.0,0.0,0.0,0.253276,2003

In [18]:
df_new["putout_time"].unique()

array([0, '1 days 00:00:00.000000000', '2 days 00:00:00.000000000',
       '3 days 00:00:00.000000000', '26 days 00:00:00.000000000',
       '9 days 00:00:00.000000000', '18 days 00:00:00.000000000',
       '5 days 00:00:00.000000000', '16 days 00:00:00.000000000',
       '19 days 00:00:00.000000000', '12 days 00:00:00.000000000',
       '6 days 00:00:00.000000000', '4 days 00:00:00.000000000',
       '167 days 00:00:00.000000000', '69 days 00:00:00.000000000',
       '8 days 00:00:00.000000000', '31 days 00:00:00.000000000',
       '36 days 00:00:00.000000000', '92 days 00:00:00.000000000',
       '91 days 00:00:00.000000000', '10 days 00:00:00.000000000',
       '11 days 00:00:00.000000000', '63 days 00:00:00.000000000',
       '118 days 00:00:00.000000000', '59 days 00:00:00.000000000',
       '93 days 00:00:00.000000000', '28 days 00:00:00.000000000',
       '50 days 00:00:00.000000000', '30 days 00:00:00.000000000',
       '7 days 00:00:00.000000000', '152 days 00:00:00.000000000',
       '15 days 00:00:00.000000000', '13 days 00:00:00.000000000',
       '25 days 00:00:00.000000000', '47 days 00:00:00.000000000',
       '55 days 00:00:00.000000000', '108 days 00:00:00.000000000',
       '39 days 00:00:00.000000000', '17 days 00:00:00.000000000',
       '54 days 00:00:00.000000000', '80 days 00:00:00.000000000',
       '20 days 00:00:00.000000000', '97 days 00:00:00.000000000',
       '84 days 00:00:00.000000000', '81 days 00:00:00.000000000',
       '22 days 00:00:00.000000000', '67 days 00:00:00.000000000',
       '14 days 00:00:00.000000000', '60 days 00:00:00.000000000',
       '62 days 00:00:00.000000000', '103 days 00:00:00.000000000',
       '24 days 00:00:00.000000000', '193 days 00:00:00.000000000',
       '117 days 00:00:00.000000000', '41 days 00:00:00.000000000',
       '61 days 00:00:00.000000000', '145 days 00:00:00.000000000',
       '94 days 00:00:00.000000000', '70 days 00:00:00.000000000',
       '43 days 00:00:00.000000000', '35 days 00:00:00.000000000',
       '40 days 00:00:00.000000000', '21 days 00:00:00.000000000',
       '65 days 00:00:00.000000000', '23 days 00:00:00.000000000',
       '89 days 00:00:00.000000000', '104 days 00:00:00.000000000',
       '106 days 00:00:00.000000000', '57 days 00:00:00.000000000',
       '90 days 00:00:00.000000000', '27 days 00:00:00.000000000',
       '46 days 00:00:00.000000000', '87 days 00:00:00.000000000',
       '74 days 00:00:00.000000000', '37 days 00:00:00.000000000',
       '42 days 00:00:00.000000000', '73 days 00:00:00.000000000',
       '148 days 00:00:00.000000000', '141 days 00:00:00.000000000',
       '122 days 00:00:00.000000000', '66 days 00:00:00.000000000',
       '44 days 00:00:00.000000000', '88 days 00:00:00.000000000',
       '161 days 00:00:00.000000000', '34 days 00:00:00.000000000',
       '132 days 00:00:00.000000000', '140 days 00:00:00.000000000',
       '45 days 00:00:00.000000000', '29 days 00:00:00.000000000',
       '102 days 00:00:00.000000000', '121 days 00:00:00.000000000',
       '51 days 00:00:00.000000000', '261 days 00:00:00.000000000',
       '77 days 00:00:00.000000000', '48 days 00:00:00.000000000',
       '71 days 00:00:00.000000000', '56 days 00:00:00.000000000',
       '79 days 00:00:00.000000000', '85 days 00:00:00.000000000',
       '222 days 00:00:00.000000000', '114 days 00:00:00.000000000',
       '76 days 00:00:00.000000000', '58 days 00:00:00.000000000',
       '72 days 00:00:00.000000000', '83 days 00:00:00.000000000',
       '131 days 00:00:00.000000000', '52 days 00:00:00.000000000',
       '112 days 00:00:00.000000000', '213 days 00:00:00.000000000',
       '68 days 00:00:00.000000000', '33 days 00:00:00.000000000',
       '101 days 00:00:00.000000000', '38 days 00:00:00.000000000',
       '99 days 00:00:00.000000000', '165 days 00:00:00.000000000',
       '119 days 00:00:00.000000000', '146 days 00:00:00.000000000',
       '136 days 00:00:00.000000000', '110 days 00:00:00.000000000',
       '255 days 00:00:00.000000000', '86 days 00:00:00.000000000',
       '49 days 00:00:00.000000000', '78 days 00:00:00.000000000',
       '96 days 00:00:00.000000000', '178 days 00:00:00.000000000', '21',
       '11', '77', '75', '87', '67', '66', '22', '10', '2', '9', '1', '6',
       '18', '12', '5', '13', '27', '7', '4', '82', '80', '3', '91', '84',
       '30', '0', '14', '94', '49', '56', '58', '33', '54', '53', '29',
       '50', '92', '23', '79', '47', '20', '115', '55', '28', '8', '73',
       '15', '72', '64', '19', '99', '39', '37', '43', '38', '101', '24',
       '112', '86', '74', '46', '110', '108', '35', '42', '44', '36',
       '59', '32', '17', '96', '88', '34', '26', '89', '116', '63', '40',
       '90', '98', '85', '16', '142', '25', '81', '52', '45', '68', '93',
       '118', '31', '48', '104', '107', '65', '129', '103', '62', '122',
       '102', '71', '121', '41', '70', '60', '144', '111', '97', '76',
       '155', '117', '57', '105', '61', '119', '113', '138', '114', '83',
       '312', '106', '95', '132', '78', '126', '164', '120', '184', '177',
       '145', '125', '109', '147', '141', '51', '139', '150', '123', '69',
       '137', '100', '128', '151', '140', '133', '146', '204', '178',
       '143', '124', '237', '153', '371', '131', '134', '170', '127'],
      dtype=object)

In [19]:
# Adding these columns to the existing dataframe.
df_new[['A', 'B']] = df_new['putout_time'].str.split(' ', 1, expand=True)

df_new

C:\Users\KATLIN\anaconda3\envs\PythonData\lib\site-packages\pandas\core\frame.py:3641: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]

,fire_size,stat_cause_descr,latitude,longitude,state,discovery_month,putout_time,Vegetation,Temp_pre_30,Temp_pre_15,...,Hum_pre_7,Hum_cont,Prec_pre_30,Prec_pre_15,Prec_pre_7,Prec_cont,remoteness,year,A,B
3,1.0,Debris Burning,39.641400,-119.308300,NV,Jun,0,0,16.275967,18.996181,...,35.353846,0.000000,10.4,7.2,0.0,0.0,0.487447,2005,NaN,NaN
9,1.0,Miscellaneous,48.839400,-99.718500,ND,Apr,0,15,4.600950,6.861878,...,54.337838,0.000000,12.3,1.8,0.0,0.0,0.291683,2004,NaN,NaN
24,40.0,Arson,31.435181,-88.999489,MS,Apr,0,12,13.468619,15.067227,...,59.614458,0.000000,0.0,0.0,0.0,0.0,0.199485,1999,NaN,NaN
26,2.0,Debris Burning,35.718900,-92.335000,AR,Jan,0,15,3.490698,0.000000,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.227270,2014,NaN,NaN
31,1.2,Debris Burning,48.833000,-99.783600,ND,Apr,0,15,-0.891635,0.372659,...,71.173116,0.000000,21.2,21.2,9.2,0.0,0.292303,2007,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55342,5086.0,Debris Burning,45.656100,-109.114200,MT,Mar,5,15,2.275974,7.360185,...,42.638384,28.844444,0.0,0.0,0.0,0.0,0.046649,2015,5,None
55343,5963.0,Debris Burning,43.785671,-115.985922,ID,Oct,10,9,17.007551,16.983670,...,56.257500,49.915194,0.0,0.0,0.0,0.0,0.060013,2015,10,None
55349,17831.0,Miscellaneous,30.005000,-100.391167,TX,Aug,6,12,28.113120,28.826531,...,58.615538,58.243619,0.0,0.0,0.0,0.0,0.451149,2015,6,None
55350,3452.0,Miscellaneous,30.400883,-101.331933,TX,Aug,2,12,31.270833,30.603352,...,47.944785,39.510638,4.6,4.6,0.0,0.0,0.429604,2015,2,None
55351,8300.0,Miscellaneous,45.922100,-111.422500,MT,Oct,5,15,12.855921,11.724403,...,66.795455,48.628099,15.8,2.8,2.8,0.0,0.009711,2015,5,None

In [20]:
df_new["A"].unique()

array([nan, '1', '2', '3', '26', '9', '18', '5', '16', '19', '12', '6',
       '4', '167', '69', '8', '31', '36', '92', '91', '10', '11', '63',
       '118', '59', '93', '28', '50', '30', '7', '152', '15', '13', '25',
       '47', '55', '108', '39', '17', '54', '80', '20', '97', '84', '81',
       '22', '67', '14', '60', '62', '103', '24', '193', '117', '41',
       '61', '145', '94', '70', '43', '35', '40', '21', '65', '23', '89',
       '104', '106', '57', '90', '27', '46', '87', '74', '37', '42', '73',
       '148', '141', '122', '66', '44', '88', '161', '34', '132', '140',
       '45', '29', '102', '121', '51', '261', '77', '48', '71', '56',
       '79', '85', '222', '114', '76', '58', '72', '83', '131', '52',
       '112', '213', '68', '33', '101', '38', '99', '165', '119', '146',
       '136', '110', '255', '86', '49', '78', '96', '178', '75', '82',
       '0', '53', '115', '64', '32', '116', '98', '142', '107', '129',
       '144', '111', '155', '105', '113', '138', '312', '95', '126',
       '164', '120', '184', '177', '125', '109', '147', '139', '150',
       '123', '137', '100', '128', '151', '133', '204', '143', '124',
       '237', '153', '371', '134', '170', '127'], dtype=object)

In [21]:
df_new[df_new["A"].isnull()]

,fire_size,stat_cause_descr,latitude,longitude,state,discovery_month,putout_time,Vegetation,Temp_pre_30,Temp_pre_15,...,Hum_pre_7,Hum_cont,Prec_pre_30,Prec_pre_15,Prec_pre_7,Prec_cont,remoteness,year,A,B
3,1.0,Debris Burning,39.641400,-119.308300,NV,Jun,0,0,16.275967,18.996181,...,35.353846,0.0,10.4,7.2,0.0,0.0,0.487447,2005,NaN,NaN
9,1.0,Miscellaneous,48.839400,-99.718500,ND,Apr,0,15,4.600950,6.861878,...,54.337838,0.0,12.3,1.8,0.0,0.0,0.291683,2004,NaN,NaN
24,40.0,Arson,31.435181,-88.999489,MS,Apr,0,12,13.468619,15.067227,...,59.614458,0.0,0.0,0.0,0.0,0.0,0.199485,1999,NaN,NaN
26,2.0,Debris Burning,35.718900,-92.335000,AR,Jan,0,15,3.490698,0.000000,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.227270,2014,NaN,NaN
31,1.2,Debris Burning,48.833000,-99.783600,ND,Apr,0,15,-0.891635,0.372659,...,71.173116,0.0,21.2,21.2,9.2,0.0,0.292303,2007,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49987,73.0,Arson,33.991263,-85.676255,AL,Aug,0,16,23.081575,23.946629,...,73.377246,0.0,0.0,0.0,0.0,0.0,0.167517,2006,NaN,NaN
49988,1.1,Debris Burning,33.717731,-83.228058,GA,Dec,0,16,8.169864,8.044944,...,74.368534,0.0,0.0,0.0,0.0,0.0,0.145718,2013,NaN,NaN
49989,3.5,Miscellaneous,42.412639,-73.674227,NY,Mar,0,9,-1.564737,0.773558,...,54.763441,0.0,57.8,19.5,2.5,0.0,0.057448,2009,NaN,NaN
49994,1.0,Miscellaneous,37.976100,-90.759000,MO,Apr,0,0,9.162112,11.540315,...,58.176353,0.0,91.6,69.4,16.0,0.0,0.211468,2014,NaN,NaN
49995,1.0,Children,47.270800,-95.621400,MN,Mar,0,15,-9.592386,-0.404299,...,76.389262,0.0,0.0,0.0,0.0,0.0,0.253276,2003,NaN,NaN

In [22]:
df_new['A'] = df_new['A'].replace(np.nan, 0)
df_new

C:\Users\KATLIN\AppData\Local\Temp/ipykernel_17864/2335287106.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new['A'] = df_new['A'].replace(np.nan, 0)

,fire_size,stat_cause_descr,latitude,longitude,state,discovery_month,putout_time,Vegetation,Temp_pre_30,Temp_pre_15,...,Hum_pre_7,Hum_cont,Prec_pre_30,Prec_pre_15,Prec_pre_7,Prec_cont,remoteness,year,A,B
3,1.0,Debris Burning,39.641400,-119.308300,NV,Jun,0,0,16.275967,18.996181,...,35.353846,0.000000,10.4,7.2,0.0,0.0,0.487447,2005,0,NaN
9,1.0,Miscellaneous,48.839400,-99.718500,ND,Apr,0,15,4.600950,6.861878,...,54.337838,0.000000,12.3,1.8,0.0,0.0,0.291683,2004,0,NaN
24,40.0,Arson,31.435181,-88.999489,MS,Apr,0,12,13.468619,15.067227,...,59.614458,0.000000,0.0,0.0,0.0,0.0,0.199485,1999,0,NaN
26,2.0,Debris Burning,35.718900,-92.335000,AR,Jan,0,15,3.490698,0.000000,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.227270,2014,0,NaN
31,1.2,Debris Burning,48.833000,-99.783600,ND,Apr,0,15,-0.891635,0.372659,...,71.173116,0.000000,21.2,21.2,9.2,0.0,0.292303,2007,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55342,5086.0,Debris Burning,45.656100,-109.114200,MT,Mar,5,15,2.275974,7.360185,...,42.638384,28.844444,0.0,0.0,0.0,0.0,0.046649,2015,5,None
55343,5963.0,Debris Burning,43.785671,-115.985922,ID,Oct,10,9,17.007551,16.983670,...,56.257500,49.915194,0.0,0.0,0.0,0.0,0.060013,2015,10,None
55349,17831.0,Miscellaneous,30.005000,-100.391167,TX,Aug,6,12,28.113120,28.826531,...,58.615538,58.243619,0.0,0.0,0.0,0.0,0.451149,2015,6,None
55350,3452.0,Miscellaneous,30.400883,-101.331933,TX,Aug,2,12,31.270833,30.603352,...,47.944785,39.510638,4.6,4.6,0.0,0.0,0.429604,2015,2,None
55351,8300.0,Miscellaneous,45.922100,-111.422500,MT,Oct,5,15,12.855921,11.724403,...,66.795455,48.628099,15.8,2.8,2.8,0.0,0.009711,2015,5,None

In [23]:
df_new.dtypes

fire_size           float64
stat_cause_descr     object
latitude            float64
longitude           float64
state                object
discovery_month      object
putout_time          object
Vegetation            int64
Temp_pre_30         float64
Temp_pre_15         float64
Temp_pre_7          float64
Temp_cont           float64
Wind_pre_30         float64
Wind_pre_15         float64
Wind_pre_7          float64
Wind_cont           float64
Hum_pre_30          float64
Hum_pre_15          float64
Hum_pre_7           float64
Hum_cont            float64
Prec_pre_30         float64
Prec_pre_15         float64
Prec_pre_7          float64
Prec_cont           float64
remoteness          float64
year                  int64
A                    object
B                    object
dtype: object

In [24]:
df_new = df_new.astype({"A":'int64'}) 
df_new.dtypes

fire_size           float64
stat_cause_descr     object
latitude            float64
longitude           float64
state                object
discovery_month      object
putout_time          object
Vegetation            int64
Temp_pre_30         float64
Temp_pre_15         float64
Temp_pre_7          float64
Temp_cont           float64
Wind_pre_30         float64
Wind_pre_15         float64
Wind_pre_7          float64
Wind_cont           float64
Hum_pre_30          float64
Hum_pre_15          float64
Hum_pre_7           float64
Hum_cont            float64
Prec_pre_30         float64
Prec_pre_15         float64
Prec_pre_7          float64
Prec_cont           float64
remoteness          float64
year                  int64
A                     int64
B                    object
dtype: object

In [25]:
df_new.rename(columns = {'A':'putout_time_int'}, inplace=True)
df_new

,fire_size,stat_cause_descr,latitude,longitude,state,discovery_month,putout_time,Vegetation,Temp_pre_30,Temp_pre_15,...,Hum_pre_7,Hum_cont,Prec_pre_30,Prec_pre_15,Prec_pre_7,Prec_cont,remoteness,year,putout_time_int,B
3,1.0,Debris Burning,39.641400,-119.308300,NV,Jun,0,0,16.275967,18.996181,...,35.353846,0.000000,10.4,7.2,0.0,0.0,0.487447,2005,0,NaN
9,1.0,Miscellaneous,48.839400,-99.718500,ND,Apr,0,15,4.600950,6.861878,...,54.337838,0.000000,12.3,1.8,0.0,0.0,0.291683,2004,0,NaN
24,40.0,Arson,31.435181,-88.999489,MS,Apr,0,12,13.468619,15.067227,...,59.614458,0.000000,0.0,0.0,0.0,0.0,0.199485,1999,0,NaN
26,2.0,Debris Burning,35.718900,-92.335000,AR,Jan,0,15,3.490698,0.000000,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.227270,2014,0,NaN
31,1.2,Debris Burning,48.833000,-99.783600,ND,Apr,0,15,-0.891635,0.372659,...,71.173116,0.000000,21.2,21.2,9.2,0.0,0.292303,2007,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55342,5086.0,Debris Burning,45.656100,-109.114200,MT,Mar,5,15,2.275974,7.360185,...,42.638384,28.844444,0.0,0.0,0.0,0.0,0.046649,2015,5,None
55343,5963.0,Debris Burning,43.785671,-115.985922,ID,Oct,10,9,17.007551,16.983670,...,56.257500,49.915194,0.0,0.0,0.0,0.0,0.060013,2015,10,None
55349,17831.0,Miscellaneous,30.005000,-100.391167,TX,Aug,6,12,28.113120,28.826531,...,58.615538,58.243619,0.0,0.0,0.0,0.0,0.451149,2015,6,None
55350,3452.0,Miscellaneous,30.400883,-101.331933,TX,Aug,2,12,31.270833,30.603352,...,47.944785,39.510638,4.6,4.6,0.0,0.0,0.429604,2015,2,None
55351,8300.0,Miscellaneous,45.922100,-111.422500,MT,Oct,5,15,12.855921,11.724403,...,66.795455,48.628099,15.8,2.8,2.8,0.0,0.009711,2015,5,None

In [26]:
df_new.drop(["putout_time", "B"], axis=1, inplace=True)
df_new

,fire_size,stat_cause_descr,latitude,longitude,state,discovery_month,Vegetation,Temp_pre_30,Temp_pre_15,Temp_pre_7,...,Hum_pre_15,Hum_pre_7,Hum_cont,Prec_pre_30,Prec_pre_15,Prec_pre_7,Prec_cont,remoteness,year,putout_time_int
3,1.0,Debris Burning,39.641400,-119.308300,NV,Jun,0,16.275967,18.996181,18.142564,...,37.140811,35.353846,0.000000,10.4,7.2,0.0,0.0,0.487447,2005,0
9,1.0,Miscellaneous,48.839400,-99.718500,ND,Apr,15,4.600950,6.861878,6.053333,...,55.943038,54.337838,0.000000,12.3,1.8,0.0,0.0,0.291683,2004,0
24,40.0,Arson,31.435181,-88.999489,MS,Apr,12,13.468619,15.067227,15.604790,...,56.747191,59.614458,0.000000,0.0,0.0,0.0,0.0,0.199485,1999,0
26,2.0,Debris Burning,35.718900,-92.335000,AR,Jan,15,3.490698,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.227270,2014,0
31,1.2,Debris Burning,48.833000,-99.783600,ND,Apr,15,-0.891635,0.372659,-4.273834,...,75.963981,71.173116,0.000000,21.2,21.2,9.2,0.0,0.292303,2007,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55342,5086.0,Debris Burning,45.656100,-109.114200,MT,Mar,15,2.275974,7.360185,7.678571,...,46.933399,42.638384,28.844444,0.0,0.0,0.0,0.0,0.046649,2015,5
55343,5963.0,Debris Burning,43.785671,-115.985922,ID,Oct,9,17.007551,16.983670,15.732906,...,53.945191,56.257500,49.915194,0.0,0.0,0.0,0.0,0.060013,2015,10
55349,17831.0,Miscellaneous,30.005000,-100.391167,TX,Aug,12,28.113120,28.826531,28.850598,...,56.987013,58.615538,58.243619,0.0,0.0,0.0,0.0,0.451149,2015,6
55350,3452.0,Miscellaneous,30.400883,-101.331933,TX,Aug,12,31.270833,30.603352,30.543452,...,47.176638,47.944785,39.510638,4.6,4.6,0.0,0.0,0.429604,2015,2
55351,8300.0,Miscellaneous,45.922100,-111.422500,MT,Oct,15,12.855921,11.724403,10.420339,...,62.120643,66.795455,48.628099,15.8,2.8,2.8,0.0,0.009711,2015,5

In [27]:
df_new.rename(columns = {'putout_time_int':'putout_time'}, inplace=True)
df_new

,fire_size,stat_cause_descr,latitude,longitude,state,discovery_month,Vegetation,Temp_pre_30,Temp_pre_15,Temp_pre_7,...,Hum_pre_15,Hum_pre_7,Hum_cont,Prec_pre_30,Prec_pre_15,Prec_pre_7,Prec_cont,remoteness,year,putout_time
3,1.0,Debris Burning,39.641400,-119.308300,NV,Jun,0,16.275967,18.996181,18.142564,...,37.140811,35.353846,0.000000,10.4,7.2,0.0,0.0,0.487447,2005,0
9,1.0,Miscellaneous,48.839400,-99.718500,ND,Apr,15,4.600950,6.861878,6.053333,...,55.943038,54.337838,0.000000,12.3,1.8,0.0,0.0,0.291683,2004,0
24,40.0,Arson,31.435181,-88.999489,MS,Apr,12,13.468619,15.067227,15.604790,...,56.747191,59.614458,0.000000,0.0,0.0,0.0,0.0,0.199485,1999,0
26,2.0,Debris Burning,35.718900,-92.335000,AR,Jan,15,3.490698,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.227270,2014,0
31,1.2,Debris Burning,48.833000,-99.783600,ND,Apr,15,-0.891635,0.372659,-4.273834,...,75.963981,71.173116,0.000000,21.2,21.2,9.2,0.0,0.292303,2007,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55342,5086.0,Debris Burning,45.656100,-109.114200,MT,Mar,15,2.275974,7.360185,7.678571,...,46.933399,42.638384,28.844444,0.0,0.0,0.0,0.0,0.046649,2015,5
55343,5963.0,Debris Burning,43.785671,-115.985922,ID,Oct,9,17.007551,16.983670,15.732906,...,53.945191,56.257500,49.915194,0.0,0.0,0.0,0.0,0.060013,2015,10
55349,17831.0,Miscellaneous,30.005000,-100.391167,TX,Aug,12,28.113120,28.826531,28.850598,...,56.987013,58.615538,58.243619,0.0,0.0,0.0,0.0,0.451149,2015,6
55350,3452.0,Miscellaneous,30.400883,-101.331933,TX,Aug,12,31.270833,30.603352,30.543452,...,47.176638,47.944785,39.510638,4.6,4.6,0.0,0.0,0.429604,2015,2
55351,8300.0,Miscellaneous,45.922100,-111.422500,MT,Oct,15,12.855921,11.724403,10.420339,...,62.120643,66.795455,48.628099,15.8,2.8,2.8,0.0,0.009711,2015,5

In [28]:
df_new=df_new.drop(columns="Vegetation")

In [31]:
df_new.rename(columns = {'stat_cause_descr':'fire_cause'}, inplace = True)
df_new

,fire_size,fire_cause,latitude,longitude,state,discovery_month,Temp_pre_30,Temp_pre_15,Temp_pre_7,Temp_cont,...,Hum_pre_15,Hum_pre_7,Hum_cont,Prec_pre_30,Prec_pre_15,Prec_pre_7,Prec_cont,remoteness,year,putout_time
3,1.0,Debris Burning,39.641400,-119.308300,NV,Jun,16.275967,18.996181,18.142564,0.000000,...,37.140811,35.353846,0.000000,10.4,7.2,0.0,0.0,0.487447,2005,0
9,1.0,Miscellaneous,48.839400,-99.718500,ND,Apr,4.600950,6.861878,6.053333,0.000000,...,55.943038,54.337838,0.000000,12.3,1.8,0.0,0.0,0.291683,2004,0
24,40.0,Arson,31.435181,-88.999489,MS,Apr,13.468619,15.067227,15.604790,0.000000,...,56.747191,59.614458,0.000000,0.0,0.0,0.0,0.0,0.199485,1999,0
26,2.0,Debris Burning,35.718900,-92.335000,AR,Jan,3.490698,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.227270,2014,0
31,1.2,Debris Burning,48.833000,-99.783600,ND,Apr,-0.891635,0.372659,-4.273834,0.000000,...,75.963981,71.173116,0.000000,21.2,21.2,9.2,0.0,0.292303,2007,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55342,5086.0,Debris Burning,45.656100,-109.114200,MT,Mar,2.275974,7.360185,7.678571,10.822222,...,46.933399,42.638384,28.844444,0.0,0.0,0.0,0.0,0.046649,2015,5
55343,5963.0,Debris Burning,43.785671,-115.985922,ID,Oct,17.007551,16.983670,15.732906,15.067251,...,53.945191,56.257500,49.915194,0.0,0.0,0.0,0.0,0.060013,2015,10
55349,17831.0,Miscellaneous,30.005000,-100.391167,TX,Aug,28.113120,28.826531,28.850598,28.250580,...,56.987013,58.615538,58.243619,0.0,0.0,0.0,0.0,0.451149,2015,6
55350,3452.0,Miscellaneous,30.400883,-101.331933,TX,Aug,31.270833,30.603352,30.543452,28.793750,...,47.176638,47.944785,39.510638,4.6,4.6,0.0,0.0,0.429604,2015,2
55351,8300.0,Miscellaneous,45.922100,-111.422500,MT,Oct,12.855921,11.724403,10.420339,11.032231,...,62.120643,66.795455,48.628099,15.8,2.8,2.8,0.0,0.009711,2015,5

In [39]:
df_new.column

AttributeError: 'DataFrame' object has no attribute 'column'

In [40]:
df_new.drop(columns="remoteness", axis=1, inplace=True)
df_new

,fire_size,fire_cause,latitude,longitude,state,discovery_month,Temp_pre_30,Temp_pre_15,Temp_pre_7,Temp_cont,...,Hum_pre_30,Hum_pre_15,Hum_pre_7,Hum_cont,Prec_pre_30,Prec_pre_15,Prec_pre_7,Prec_cont,year,putout_time
3,1.0,Debris Burning,39.641400,-119.308300,NV,Jun,16.275967,18.996181,18.142564,0.000000,...,44.778429,37.140811,35.353846,0.000000,10.4,7.2,0.0,0.0,2005,0
9,1.0,Miscellaneous,48.839400,-99.718500,ND,Apr,4.600950,6.861878,6.053333,0.000000,...,64.606509,55.943038,54.337838,0.000000,12.3,1.8,0.0,0.0,2004,0
24,40.0,Arson,31.435181,-88.999489,MS,Apr,13.468619,15.067227,15.604790,0.000000,...,57.997207,56.747191,59.614458,0.000000,0.0,0.0,0.0,0.0,1999,0
26,2.0,Debris Burning,35.718900,-92.335000,AR,Jan,3.490698,0.000000,0.000000,0.000000,...,76.091398,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,2014,0
31,1.2,Debris Burning,48.833000,-99.783600,ND,Apr,-0.891635,0.372659,-4.273834,0.000000,...,77.575012,75.963981,71.173116,0.000000,21.2,21.2,9.2,0.0,2007,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55342,5086.0,Debris Burning,45.656100,-109.114200,MT,Mar,2.275974,7.360185,7.678571,10.822222,...,51.676681,46.933399,42.638384,28.844444,0.0,0.0,0.0,0.0,2015,5
55343,5963.0,Debris Burning,43.785671,-115.985922,ID,Oct,17.007551,16.983670,15.732906,15.067251,...,51.541802,53.945191,56.257500,49.915194,0.0,0.0,0.0,0.0,2015,10
55349,17831.0,Miscellaneous,30.005000,-100.391167,TX,Aug,28.113120,28.826531,28.850598,28.250580,...,60.470917,56.987013,58.615538,58.243619,0.0,0.0,0.0,0.0,2015,6
55350,3452.0,Miscellaneous,30.400883,-101.331933,TX,Aug,31.270833,30.603352,30.543452,28.793750,...,44.411268,47.176638,47.944785,39.510638,4.6,4.6,0.0,0.0,2015,2
55351,8300.0,Miscellaneous,45.922100,-111.422500,MT,Oct,12.855921,11.724403,10.420339,11.032231,...,60.914780,62.120643,66.795455,48.628099,15.8,2.8,2.8,0.0,2015,5

In [41]:
df_new.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 18918 entries, 3 to 55351
Data columns (total 24 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   fire_size        18918 non-null  float64
 1   fire_cause       18918 non-null  object
 2   latitude         18918 non-null  float64
 3   longitude        18918 non-null  float64
 4   state            18918 non-null  object
 5   discovery_month  18918 non-null  object
 6   Temp_pre_30      18918 non-null  float64
 7   Temp_pre_15      18918 non-null  float64
 8   Temp_pre_7       18918 non-null  float64
 9   Temp_cont        18918 non-null  float64
 10  Wind_pre_30      18918 non-null  float64
 11  Wind_pre_15      18918 non-null  float64
 12  Wind_pre_7       18918 non-null  float64
 13  Wind_cont        18918 non-null  float64
 14  Hum_pre_30       18918 non-null  float64
 15  Hum_pre_15       18918 non-null  float64
 16  Hum_pre_7        18918 non-null  float64
 17  Hum_cont         18918 non-null  float64
 18  Prec_pre_30      18918 non-null  float64
 19  Prec_pre_15      18918 non-null  float64
 20  Prec_pre_7       18918 non-null  float64
 21  Prec_cont        18918 non-null  float64
 22  year             18918 non-null  int64
 23  putout_time      18918 non-null  int64
dtypes: float64(19), int64(2), object(3)
memory usage: 3.6+ MB

In [42]:
df_new.to_csv("Resources/cleaned_wildfire_7.csv")